### ISSUE TITLE
Target Cast Bar

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#10]
I've attempted to include this frame, but unfortunately it seems Blizzard has code that moves it back to just under the Target Frame again. The position is based on how many buffs your target has, and is constantly being updated. This means moving the Target's Cast Bar is not simple, and may not even be possible.

**Comment by kpontussvensson** [comment]
That's too bad. I guess it's the same with the focus cast bar in that case then?

**Comment by kpontussvensson** [comment]
Looking at the macro I use for moving my target and focus cast bars it seems the function Blizzard uses is just the .SetPoint function. The macro seems to override this with just an empty function:

```
/run FocusFrameSpellBar:ClearAllPoints();FocusFrameSpellBar:SetPoint("BOTTOMLEFT", FocusFrame, "TOPLEFT", 37, 0);FocusFrameSpellBar.SetPoint = function() end;FocusFrameSpellBar:SetScale(1.4)
```

**Comment by teelolws** [comment]
Your macro replaces the SetPoint, which is risky. Blizzard code will be calling that, and since you've blanked it out, you'll be tainting Blizzards execution. I need to be certain that taint won't lead to any "action blocked" errors before I can use it.
