### ISSUE TITLE
Bug?: Talking Head

### ISSUE THREAD

**Issue by nancikennedy** [teelolws/EditModeExpanded#101]
Sometime in the last 10ish days, I noticed layer weirdness with (as it turned out) the Talking Head frame (unless "Hide" is checked). Any UI frame, base or addon, that is open is acting like the Talking Head is above it (but not visible because it's not "active") so no mouse input is registering. Opening up Edit Mode and closing it immediately solves the problem until the next login.

**Comment by nancikennedy** [comment]
Sorry... Using v10.1-014 on Retail

**Comment by teelolws** [comment]
Can you find some steps that will always cause the problem after a /reload?

**Comment by teelolws** [comment]
I don't see anything there about the LFG icon. They just gave the premade finder tool button some colour.

**Comment by Piskemannen** [comment]
Oh I'm blind, what the hell is the point of minimap button if the micromenu icon does the same?

**Comment by teelolws** [comment]
The minimap button is to remind you you're currently queued.

**Comment by Piskemannen** [comment]
Blizzard could just make every micromenu button interactive and you'd use keyboard to actually open Group Finder for example.

**Comment by teelolws** [comment]
Mine is not to question why Blizzard added buttons, only to let us move them!

**Comment by Piskemannen** [comment]
I hope some day you will tip your toe into full on UI overhaul :)
