### ISSUE TITLE
Bug: Menu Bar

### ISSUE THREAD

**Issue by nancikennedy** [teelolws/EditModeExpanded#102]
Using v10.1-014 on Retail, after the last update (to .x.14) on login OR reloading the client, the bar is shifted slightly to the right from it's specified position. Opening/closing Edit Mode fixes this temporarily

**Comment by teelolws** [comment]
Got it. I hadn't noticed this one as I always kept the bar at the bottom right, so it was being pushed back inside the screen again.

**Comment by Piskemannen** [comment]
Hi again, is it possible to make default round buttons on the minimap to have a square option?
