### ISSUE TITLE
Disable highlighting

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#103]
Hi again, is it possible to make default round buttons on the minimap to have a square option?

_Originally posted by @Piskemannen in https://github.com/teelolws/EditModeExpanded/issues/102#issuecomment-1571086435_

**Comment by teelolws** [comment]
Can you show me which buttons you mean?

**Comment by Piskemannen** [comment]
These two. Not sure if there's more default round buttons.
![1](https://github.com/teelolws/EditModeExpanded/assets/133789008/70e2d052-cfd2-4a72-aaf7-97f114abb549)

**Comment by teelolws** [comment]
I can't change the Expansion one - its actually a different shape every expansion. In shadowlands it was a different shape for each covenant.

As for the LFG button - maybe. I'll see if its possible

**Comment by Piskemannen** [comment]
Also is there any possible way to disable the blue bar over every single thing, when using the edit mode? It makes it hard to fine-tune the UI imo.

**Comment by Piskemannen** [comment]
Is it possible to make a popup button for the expansion button you think? That way, it doesn't matter what shape those are. 

Yeah, I think Blizzard did a sloppy job with the Edit Mode. Every UI addon I've ever tried ALWAYS shows everything you can edit, not just an empty bar...

**Comment by teelolws** [comment]
What do you imagine this "popup button" would look like / how would it work?

**Comment by Piskemannen** [comment]
It would be a square button, possibly integrated somewhere on the minimap, like how the Tracking/Calendar/AddOn buttons are. You click on it and then the buttons for EVERY expansion that has them, will show up. 

I remember years ago that was possible by default, nowadays I have problems getting the correct button to appear, even when IN the current location of x expansion.

**Comment by teelolws** [comment]
There is this addon that will give you an expansion menu: https://www.curseforge.com/wow/addons/mission-report-button-plus

I'm not that keen to completely redesign the button though. That would be better for a dedicated addon to handle.

**Comment by Piskemannen** [comment]
That's a great one, thanks! How keen are you on doing an overhual of the default Edit Mode? To be more fine tuned, like make a way to get empty bars to actually show what will be there, and reduce the size of blue boxes to be slightly smaller than what you're actually moving.

**Comment by teelolws** [comment]
My goal with this addon is to *expand* edit mode, to cover frames and features that Blizzard left out. For how edit mode works - I'm trying to respect how they originally designed it as much as possible.

For the empty bars - every single bar that is empty, I tried to find a way to give it default data during Edit Mode but found it impossible, giving it fake data caused things to break. Some of them I actually made it work, like the achievements alert - I made it pop up an achievement when its clicked on.

For fine tuning it - if you're trying to get frames in a pixel perfect position, you can move them a single pixel with arrow keys. I will look into an option to hide all the blue bars.

**Comment by teelolws** [comment]
Probably all/none, I can't always know if a box has anything showing in it.

**Comment by teelolws** [comment]
Looks really weird with all the blue bars gone:

![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/64d40df3-fae0-44f7-83b1-8bd21e77c015)

I'll continue it tomorrow. Next step is to find somewhere to put the toggle option.

**Comment by Piskemannen** [comment]
It looks pretty good for now imo. I know this is a big ask, but would there be less issues/bugs if you made an addon that would take over the entire Edit Mode?

**Comment by teelolws** [comment]
There are already addons that do that. MoveAnything. BlizzMove. Dominos. A bunch of others I forget.

I can't do a true takeover anyway, most of the action bars, target frames, basically anything with a button you can press that actually does stuff at the game level - casts spells, changes target, I'm quite limited with what I can do.

Those other addons get around those restrictions by completely replacing the bars and buttons with their own copy. Thats a step beyond what I'm trying for here. This addon is for people who like the default UI - it just adds stuff Blizzard forgot about.

**Comment by Piskemannen** [comment]
After Df, I really like the default UI for the most part. Had ElvUI for years, but moved away from it due to wanting a little more simplicity, no need to have 100+ movable things. Btw is there any plans to add more widgets to move, or GM ticket frame, perhaps improve the chat box a little.

**Comment by teelolws** [comment]
I don't have "plans". If you ask for something, I'll see if I can do it.

GM ticket frame: maybe, though I don't want to open a ticket just to test it.

Chat box: what do you have in mind?

**Comment by Piskemannen** [comment]
For chat box I'd like to hide buttons like Social, Chat Channel, Chat Bubble. Maybe be able to copy links. Definitely hide that terrible Quick Join crap! 

Did you look more into why the default bag is so high up and can't be moved to bottom/edge of screen? I simply hate having several addons just for one thing.

**Comment by teelolws** [comment]
For copying links: https://www.curseforge.com/wow/addons/chat-copy-paste

The bags are a toggled popup window - that puts it out of scope for this addon. I've heard Blizzard are possibly adding things like that in to Edit Mode in a future patch though.

**Comment by teelolws** [comment]
Thats a no to changing the LFG eye to square. The internal icons are already a circle, changing it to square would require a new animation and a complete redesign of the button:
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/6832874c-8f41-4938-a5a8-e6664a58cf6f)

**Comment by teelolws** [comment]
Option to hide the selection box shading added.

Before:
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/510ff5e6-f611-43c0-a6ba-eeb3d3344f38)

After:
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/48234285-5b3d-42f2-8c0e-d07863f05292)
