### ISSUE TITLE
Raid Control panel pops up after combat no group/grouped.

### ISSUE THREAD

**Issue by InsaneToons** [teelolws/EditModeExpanded#106]
Hello i am using EditModeExpanded-10.1-016. when i leave combat the raid control panel pops up like i opened it except its blank but when i click the arrow to hide/unhide it, it shows the controls like normal. i disabled all addons except EME and it produced the same results and then was fine with no addons enabled. it happens when not in a party or raid and when in a party/raid.
![WoWScrnShot_061823_225907](https://github.com/teelolws/EditModeExpanded/assets/137030281/942398e0-75f9-4f6b-8690-2da3d6ee8d4d)
![WoWScrnShot_061823_225917](https://github.com/teelolws/EditModeExpanded/assets/137030281/6ace01a0-3d18-4511-b8c7-9df08eb27687)

**Comment by teelolws** [comment]
Can you show me your options when you open it during Edit Mode:

![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/5748de46-3d35-48b3-b042-59f036ee40d8)

**Comment by InsaneToons** [comment]
![image](https://github.com/teelolws/EditModeExpanded/assets/137030281/c2c2bbc6-85f0-4159-afc4-ff0a0e5219c9)

**Comment by teelolws** [comment]
Thanks. This should fix it.
