### ISSUE TITLE
Micromenu is massive now

### ISSUE THREAD

**Issue by Piskemannen** [teelolws/EditModeExpanded#108]
Even with menu size at 100% (it can't go lower), it's way larger than what it was before this patch. Can you add a toggle to this that goes below 100% size?

**Comment by teelolws** [comment]
Yeah I'm going to add the size slider back to it. Just need to do some more testing, to make sure two sliders doesn't cause any issues.

**Comment by Piskemannen** [comment]
Thanks for fixing this! Well, that's what indie companies do.

**Comment by teelolws** [comment]
Okay, its back to how it used to be. It'll need to be turned on with this option:
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/83d2408c-f084-48ea-9dba-50f7c7a29f96)

This is to avoid confusion from having two resize bars.

**Comment by Piskemannen** [comment]
How do you get that interface to show? I only have one called Expanded on right side of HUD Edit Mode (with far less options).

**Comment by teelolws** [comment]
Escape > Options > Addons

**Comment by Piskemannen** [comment]
Great! 75% is the ideal scale for my UI.
