### ISSUE TITLE
Soul Shards Positioning Issue

### ISSUE THREAD

**Issue by class2u** [teelolws/EditModeExpanded#109]
1. Open Edit Mode.
2. Click the Reset button of Soul Shards.
3. Move Soul Shards frame to a different place.
4. Exit Edit Mode.
The Soul Shards frame goes back to the original place. Not staying where I moved it to.
I am using Edit Mode Expanded 10.1-022 with zhTW client.

**Comment by teelolws** [comment]
Thanks! I see the problem.
