### ISSUE TITLE
More UI elements to add

### ISSUE THREAD

**Issue by dhaern** [teelolws/EditModeExpanded#11]
Checking another addon like MoveAny:

https://www.curseforge.com/wow/addons/moveany

I have a few suggestion to add more UI elements like Target of target, castbar from target of target and castbar from Focus. Also Alert frames like the achievements or the battle.net online/offline friends and the durability doll.

Thanks.

**Comment by teelolws** [comment]
I was looking into the Castbars earlier today actually. I can't find a way to make it possible without breaking things. Blizzard is constantly updating the position of the Castbars based on how many buffs the target / target of target / focus has. If I try and make them stop moving it, or try and move it back while in combat, I get errors.

**Comment by teelolws** [comment]
Duplicate: https://github.com/teelolws/EditModeExpanded/issues/10
