### ISSUE TITLE
Bug with Raid Manager

### ISSUE THREAD

**Issue by MetalHeadSeven** [teelolws/EditModeExpanded#110]
There is an issue Raid Manager.  It stays fully extended instead of retracting to the side of the screen like normal.  If I click the arrow that would normally close it it alternates between fully extended normal and fully extended blank.  I've tried clicking Raid Manager Reset but that has no effect.  If I disable EditModeExpanded the frame returns to normal behavior.  I'm not getting any errors.

![RM (1)](https://github.com/teelolws/EditModeExpanded/assets/34187628/5d807cb6-f377-4cff-ad17-6cb32e2d6e19)

![RM (2)](https://github.com/teelolws/EditModeExpanded/assets/34187628/bf0d981d-39fc-4064-b179-e01f15086bf7)

**Comment by teelolws** [comment]
It does that the first time you use the addon on a profile - you have to uncheck "clamp to screen" to move it back left. Its a bug on my list to fix!

**Comment by MetalHeadSeven** [comment]
Thanks for the fast response.  That resolved the issue. 

Great Addon improves edit mode so much!
