### ISSUE TITLE
Protected Function Error

### ISSUE THREAD

**Issue by MetalHeadSeven** [teelolws/EditModeExpanded#114]
Getting this error and I don't even use Party Frames.

1x [ADDON_ACTION_BLOCKED] AddOn 'EditModeExpanded' tried to call the protected function 'PartyFrame:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:138: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:1177: in function <FrameXML/EditModeManager.lua:1175>
[string "=[C]"]: in function `secureexecuterange'
[string "@FrameXML/EditModeManager.lua"]:1181: in function `InitSystemAnchors'
[string "@FrameXML/EditModeManager.lua"]:963: in function `UpdateLayoutInfo'
[string "@FrameXML/EditModeManager.lua"]:258: in function <FrameXML/EditModeManager.lua:250>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by teelolws** [comment]
What were you doing when it happened? And what are your Party Frame settings?
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/dd945fe2-28f4-4c9c-abed-89af2034987d)

**Comment by MetalHeadSeven** [comment]
I was questing solo in Northern Barrens.

**Comment by MetalHeadSeven** [comment]
![Party](https://github.com/teelolws/EditModeExpanded/assets/34187628/c206945b-9de8-4b54-9dbd-ac172bdc21b6)

**Comment by teelolws** [comment]
I've been trying to recreate the issue with no luck. Unless you can find a set of steps that always causes this error to happen, with all other addons disabled, unfortunately I probably won't be able to help with this.

**Comment by MetalHeadSeven** [comment]
OK no problem and thanks for looking into it.  It happened twice yesterday and nothing since then so hopefully it was just a weird glitch.
