### ISSUE TITLE
Buggy

### ISSUE THREAD

**Issue by DakHarding** [teelolws/EditModeExpanded#115]
Retail.

- Conflicting with main interface and throwing up errors in BugGrabber.
- Doesn't want to save properly. For instance, when UNchecking Target Cast Bar, it still shows. Reload, logging out, trying again. Nothing works. It's literally unchecked everywhere in the addon options menu and edit UI itself, yet still shows up on screen.
- Randomly resets UI elements for no reason forcing to go back in, readjust, hitting save, and hoping it actually saves.

I don't know. Very buggy for something that should be simple.

**Comment by teelolws** [comment]
Can you show me the error
