### ISSUE TITLE
Focus Cast Bar not aligned.

### ISSUE THREAD

**Issue by InsaneToons** [teelolws/EditModeExpanded#116]
seems like the X and Y position of the Focus Cast Bar is off from the anchor point for the actual frame. 
It seems to save the position if you close out of the actual edit mode window, doesn't save position when you close out the smaller window, tested with and without other addons on.
Using latest release/EditModeExpanded-10.1-032
![Focus Cast Bar](https://github.com/teelolws/EditModeExpanded/assets/137030281/5d3aa5c4-c3dd-4ce0-97a1-8fdab67bae69)

**Comment by teelolws** [comment]
Did some testing - it only happens if I have "Snap to Elements" turned on. Not sure why thats affecting it though. I don't use that in the addon.

**Comment by teelolws** [comment]
This should fix the issue. Since 10.1.7 releases tomorrow I'll hold this update to go with the patch.
