### ISSUE TITLE
Options Error

### ISSUE THREAD

**Issue by OttoDeFe** [teelolws/EditModeExpanded#118]
Getting this when trying to access the options through the settings menu:

`["message"] = "Interface/AddOns/EditModeExpanded/Options.lua:96: attempt to index field 'db' (a nil value)",
			["time"] = "2023/09/16 11:20:09",
			["locals"] = "info = <table> {\n 0 = \"EditModeExpanded\"\n options = <table> {\n }\n option = <table> {\n }\n appName = \"EditModeExpanded\"\n uiType = \"dialog\"\n uiName = \"AceConfigDialog-3.0\"\n type = \"toggle\"\n 1 = \"achievementAlert\"\n}\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index field 'db' (a nil value)\"\n",
			["stack"] = "[string \"@Interface/AddOns/EditModeExpanded/Options.lua\"]:96: in function `member'\n[string \"@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua\"]:215: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:164>\n[string \"@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua\"]:1193: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>\n[string \"@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua\"]:1639: in function `FeedGroup'\n[string \"@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua\"]:1919: in function `Open'\n[string \"@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua\"]:1947: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1945>\n[string \"=[C]\"]: ?\n[string \"@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua\"]:66: in function <Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>\n[string \"@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua\"]:300: in function `Fire'\n[string \"@Interface/AddOns/Ace3/AceGUI-3.0-41/widgets/AceGUIContainer-BlizOptionsGroup.lua\"]:20: in function <...GUI-3.0/widgets/AceGUIContainer-BlizOptionsGroup.lua:19>\n[string \"=[C]\"]: in function `Show'\n[string \"@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua\"]:930: in function `DisplayLayout'\n[string \"@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua\"]:875: in function `DisplayCategory'\n[string \"@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua\"]:817: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:810>\n[string \"=[C]\"]: ?\n[string \"@Interface/SharedXML/CallbackRegistry.lua\"]:178: in function <Interface/SharedXML/CallbackRegistry.lua:177>\n[string \"=[C]\"]: ?\n[string \"@Interface/SharedXML/CallbackRegistry.lua\"]:181: in function `TriggerEvent'\n[string \"@Interface/SharedXML/Settings/Blizzard_CategoryList.lua\"]:150: in function <...terface/SharedXML/Settings/Blizzard_CategoryList.lua:148>",
			["session"] = 8913,
			["counter"] = 1,`

I'm also seeing the Zone Name background below the minimap cluster, but the mouseover only works in the area where it would be if not moved. The texture also ignores any mouseover fading.

**Comment by teelolws** [comment]
Whoops!
