### ISSUE TITLE
Bug: Math nil error when moving frames

### ISSUE THREAD

**Issue by nancikennedy** [teelolws/EditModeExpanded#121]
On Retail, using v10.1-039:

Suddenly today when I logged in and tried to move anything in Edit Mode, EDE is throwing up an error, the relocated position is not registering, and there is no way to save the changed position.

243x FrameXML/EditModeSystemTemplates.lua:535: attempt to perform arithmetic on local 'left' (a nil value)
[string "@FrameXML/EditModeSystemTemplates.lua"]:535: in function `GetScaledSelectionSides'
[string "@FrameXML/EditModeSystemTemplates.lua"]:507: in function `IsVerticallyAlignedWithFrame'
[string "@FrameXML/EditModeSystemTemplates.lua"]:725: in function `GetFrameMagneticEligibility'
[string "@FrameXML/EditModeUtil.lua"]:130: in function `GetEligibleMagneticFrames'
[string "@FrameXML/EditModeUtil.lua"]:283: in function `FindMagneticFrames'
[string "@FrameXML/EditModeUtil.lua"]:367: in function `GetMagneticFrameInfo'
[string "@FrameXML/EditModeManager.lua"]:1063: in function `RefreshSnapPreviewLines'
[string "@FrameXML/EditModeManager.lua"]:170: in function <FrameXML/EditModeManager.lua:168>

Locals:
self = EncounterBar {
 0 = <userdata>
 UpdateMagnetismRegistration = <function> defined @FrameXML/EditModeSystemTemplates.lua:731
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:609
 systemInfo = <table> {
 }
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:694
 TrySetCompositeNumberSettingValue = <function> defined @FrameXML/EditModeSystemTemplates.lua:212
 downKeys = <table> {
 }
 LayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:209
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:540
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:254
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:532
 SelectSystem = <function> defined =[C]:-1
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:714
 CalculateFrameSize = <function> defined @SharedXML/LayoutFrame.lua:165
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:499
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @FrameXML/EditModeSystemTemplates.lua:381
 GetScaledCenter = <function> defined @FrameXML/EditModeSystemTemplates.lua:525
 EMEanchorTo = UIParent {
 }
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:445
 UpdateDisplayInfoOptions = <function> defined @FrameXML/EditModeSystemTemplates.lua:456
 GetSystemName = <function> defined @FrameXML/EditModeSystemTemplates.lua:822
 ProcessMovementKey = <function> defined @FrameXML/EditModeSystemTemplates.lua:39
 GetSettingValueBool = <function> defined @FrameXML/EditModeSystemTemplates.lua:436
 HasCompositeNumberSetting = <function> defined @FrameXML/EditModeSystemTemplates.lua:385
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:440
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 ShouldResetSettingsDialogAnchors = <function> defined @FrameXML/EditModeSystemTemplates.lua:168
 EMEanchorPoint = "BOTTOMLEFT"
 GetChildPadding = <function> defined @SharedXML/LayoutFrame.lua:150
 EMESystemID = 37
 isManagedFrame = true
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:481
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:465
 hasActiveChanges = false
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:653
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:596
 SetupSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:369
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:330
 isBottomManagedFrame = true
 UpdateDirtySettings = <function> defined @FrameXML/EditModeSystemTemplates.lua:189
 isHighlighted = true
 BreakSnappedFrames = <function> defined @FrameXML/EditModeSystemTemplates.lua:636
 PrepareForSave = <function> defined @FrameXML/EditModeSystemTemplates.lua:97
 snappedFrames = <table> {
 }
 SetPointOverride = <function> defined @FrameXML/EditModeSystemTemplates.lua:137
 UpdateClampOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:148
 ignoreFramePositionManager = true
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:40
 OnAnyEditModeSystemAnchorChanged = <function> defined @FrameXML/EditModeSystemTemplates.lua:828
 GetManagedFrameContainer

**Comment by teelolws** [comment]
That one sounds familiar. I remember early on in Dragonflight people (who weren't using my addon) reporting that error. Does it still happen without my addon?

**Comment by nancikennedy** [comment]
Thanks for the heads up. I had already recreated my layout to get rid of the error, but I will note this for the future!
