### ISSUE TITLE
Bag UI moving to default position every time I enter combat

### ISSUE THREAD

**Issue by Piskemannen** [teelolws/EditModeExpanded#123]
As title states. Once I exit combat it goes back to the position I set using edit mode.

**Comment by teelolws** [comment]
I'm trying to find a way to recreate your issue. Can you show me your bag bar settings?

![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/c1be0d8d-432b-43c1-ade8-8c925c341b12)

**Comment by Piskemannen** [comment]
My bag settings is just like yours, but I have "Hide" checked.

**Comment by teelolws** [comment]
Is the problem with your bag bar or the backpack?

**Comment by teelolws** [comment]
So for the backpack, I can't move it while you're in combat. When you close and open the backpack, Blizzard moves the backpack back to its default position, which is usually either the bottom right side of your screen, or anchored to one of your action bars on the right of your screen. If you're out of combat, my addon will quickly move the backpack over to your custom position you set during Edit Mode, but if you're in combat, my addon can't do anything so the backpack will stay at the default position until you close and reopen it outside combat.

This is a limitation of the UI I unfortunately cannot do anything about!

**Comment by Piskemannen** [comment]
No problem! At least I know why it happens.
