### ISSUE TITLE
Player special bar does not stay in place. [Conflict with EasyFrames addon]

### ISSUE THREAD

**Issue by Maximos7** [teelolws/EditModeExpanded#125]
Hello. In a collision with Easy Frames addon (im certain cause i tried with only these 2 addons enabled) the Player special bar (DK runes etc) does not stay in place when moved. Ofc i tried the option to unlink them from the player unitframe but again at the moment i move the runes it resets to the default potision under the player unitframe. If i dont enable EF then it works as intented. Could you pls fix this? Thank you!

**Comment by teelolws** [comment]
Its the code in EasyFrames\Modules\Core.lua inside `function Core:MovePlayerPowerBar()` doing it. The code is moving the power bar slightly from the game's default to a position that works around that addons slightly different shape and size. The addon doesn't come with an option to stop moving it and I can't stop another addon from doing something.

In Core.lua at line 253 just after `function Core:MovePlayerPowerBar()`, adding `if true then return end` stopped it happening. Ideally the author will add an option to disable that function properly.

**Comment by Maximos7** [comment]
Ty for the reply. So, if i do this ''In Core.lua at line 253 just after function Core:MovePlayerPowerBar(), adding if true then return end stopped it happening'' you think it will work?

**Comment by teelolws** [comment]
Only one way to find out!

**Comment by Maximos7** [comment]
Yes! It works! I did it like this and it moved and stayed there ^^. Hope EF author fixes it :)
function Core:MovePlayerPowerBar()
if true then return end

**Comment by Revnn** [comment]
Jesus, since it was only dk rune power i didn't think to look into other addons.
I had Moveit moving the rune power bar. Sorry and ty.
