### ISSUE TITLE
Errors when opening edit mode

### ISSUE THREAD

**Issue by ChloeMarie** [teelolws/EditModeExpanded#128]
I opened edit mode and my chat box filled with error warnings. There were a few things that didn't move when I tried to drag them and some blank boxes that didn't have a popup showing what they were (or move) when I clicked on them. 

This is what bug grabber caught:

20x ...d/libs/EditModeExpanded-1.0-74/EditModeExpanded-1.0.lua:1002: attempt to index field '?' (a nil value)
[string "@EditModeExpanded/libs/EditModeExpanded-1.0-74/EditModeExpanded-1.0.lua"]:1002: in function `UpdateSettings'
[string "@FrameXML/EditModeDialogs.lua"]:359: in function `UpdateDialog'
[string "@FrameXML/EditModeDialogs.lua"]:340: in function `AttachToSystemFrame'
[string "@EditModeExpanded/libs/EditModeExpanded-1.0-74/EditModeExpanded-1.0.lua"]:145: in function <...d/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:143>
[string "=[C]"]: in function `SelectSystem'
[string "@FrameXML/EditModeManager.lua"]:721: in function <FrameXML/EditModeManager.lua:719>
[string "=[C]"]: in function `secureexecuterange'
[string "@FrameXML/EditModeManager.lua"]:729: in function <FrameXML/EditModeManager.lua:717>
[string "=[C]"]: in function `SelectSystem'
[string "@FrameXML/EditModeSystemTemplates.lua"]:2467: in function <FrameXML/EditModeSystemTemplates.lua:2466>

Locals:
self = EditModeExpandedSystemSettingsDialog {
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 Border = Frame {
 }
 SetHeightPadding = <function> defined @SharedXML/LayoutFrame.lua:160
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:131
 OnKeyDown = <function> defined @FrameXML/EditModeDialogs.lua:310
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:93
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:85
 GetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:156
 OnShow = <function> defined @SharedXML/LayoutFrame.lua:32
 GetHeightPadding = <function> defined @SharedXML/LayoutFrame.lua:164
 OnDragStop = <function> defined @FrameXML/EditModeDialogs.lua:332
 GetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:148
 dirty = false
 ReleaseAllNonSliders = <function> defined @FrameXML/EditModeDialogs.lua:375
 GetWidthPadding = <function> defined @SharedXML/LayoutFrame.lua:168
 resetDialogAnchors = true
 widthPadding = 40
 OnSettingInteractEnd = <function> defined @FrameXML/EditModeDialogs.lua:476
 OnSettingValueChanged = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1105
 Buttons = Frame {
 }
 Settings = Frame {
 }
 0 = <userdata>
 SetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:135
 UpdateButtons = <function> defined @FrameXML/EditModeDialogs.lua:447
 Title = FontString {
 }
 heightPadding = 40
 GetFixedHeight = <function> defined @SharedXML/LayoutFrame.lua:152
 UpdateSettings = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:923
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:117
 pools = <table> {
 }
 SetFixedHeight = <function> defined @SharedXML/LayoutFrame.lua:139
 OnDragStart = <function> defined @FrameXML/EditModeDialogs.lua:328
 GetSettingPool = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1074
 SetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:143
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:73
 UpdateSizeAndAnchors = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:845
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 attachedToSystem = MinimapCluster {
 }
 onCloseCallback = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1119
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:127
 OnLoad = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1118
 OnHide = <function> defined @FrameXML/EditModeDialogs.lua:303
 Layout = <function> defined @SharedXML/LayoutFrame.lua:395
 AttachToSystemFrame = <function> defined @FrameXML/EditModeDialogs.lua:336
 RevertChanges = <function> defined @FrameXML/EditModeDialogs.lua:485
 ReleaseNonDraggingSliders = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1085
 CloseButton = Button {
 }
 UpdateDialog = <function> defined @FrameXML/EditModeDialogs.lua:358
 OnKeyUp = <function> defined @FrameXML/EditModeDialogs.lua:322
 MarkIgnoreInLayout = <function> defined @SharedXML/LayoutFrame.lua:44
 OnSettingInteractStart = <function> defined @FrameXML/EditModeDialogs.lua:467
 UpdateExtraButtons = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:857
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:391
}
systemFrame = MinimapCluster {
 0 = <userdata>
 UpdateMagnetismRegistration = <fu

**Comment by teelolws** [comment]
This should fix it, let me know if it keeps happening.
