### ISSUE TITLE
Pet Frame missing

### ISSUE THREAD

**Issue by IskrenTs** [teelolws/EditModeExpanded#13]
I have tried everything but the pet frame is missing if your addon is on. The moment i disable your addon it shows again. And yes i have tested with only your addon enabled and no other addons.

**Comment by teelolws** [comment]
Thanks. Disabling PetFrame support until I can find the cause of this issue.

**Comment by teelolws** [comment]
Pushing a patch now bringing back Pet Frame support. Use the Reset button if the frame is still not there. If its still not working, let me know.
