### ISSUE TITLE
Expansion Button won't show

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#131]
TBH I don't know if this is an add-on issue or a game UI issue but the Expansion Button has disappeared for me today (maybe earlier but I only noticed today).  When I'm in edit mode I can see it and I can toggle the Hide option but no matter which setting I select it disappears once I get out of edit mode.

**Comment by teelolws** [comment]
Noticing this too. Its there when I /reload, but soon as I enter Edit Mode it disappears.

**Comment by teelolws** [comment]
Allright, narrowed it down to another addon having an outdated version of the EditModeExpanded library embedded. I've updated the one in [Dragonriding Speedrun](https://github.com/teelolws/Dragonriding_Speedrun), but if theres any other addons that use it, they'll need to update it themselves.

**Comment by teelolws** [comment]
Took me a while to figure out why its not showing during edit mode, turned out I just had it unchecked here:
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/8749f5a9-3924-4744-846f-a5772803545a)

**Comment by raysmith59** [comment]
Yeah, it's back working today so either a conflicting add-on was updated or they fixed it during the weekly maintenance.
