### ISSUE TITLE
Is there a way to not have certain things move / become detached? Example - Target Cast Bar / Player Combo Points

### ISSUE THREAD

**Issue by daibosu** [teelolws/EditModeExpanded#133]
Is there a way to not have certain things move / become detached? Example - Target Cast Bar / Player Combo Points?

Combo Points for example I have to manually put in position, but I would rather it be wherever / attached to whatever the default UI would have been. Clicking reset, just places the combo points for example on a random part of my screen.

**Comment by teelolws** [comment]
Yup, just go into the addon options and disable that module!

![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/01aea8ae-fa58-4056-a232-acc3b8fb733b)

**Comment by daibosu** [comment]
Ah perfect that's what I was missing, kept trying to uncheck thing inside the edit UI menu. Thank you.

**Comment by teelolws** [comment]
Unchecking inside the edit UI menu does the same thing as the other checkboxes in the base UI: it just stops it showing during edit mode!
