### ISSUE TITLE
LFG button is tiny after reload

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#134]
Not a big deal but for a while now the LFG button has been tiny... if I reset IT in the EME UI it move bottom-right on my screen but goes back to normal size, at that point I move it to the usual spot on the minimap, but after the next reload/relog (hearthing didn't affect it) it goes small again and moves to the middle of the screen.  In a quick test this happens even with just EME enabed so I don't think it's an add-on conflict.  I have a 3440x1440 display in case that's somehow a factor.

**Comment by teelolws** [comment]
Problems like this are usually caused by another addon trying to take control of the button. Does it happen with your other addons disabled?

**Comment by raysmith59** [comment]
Yes; even without any other add-ons loaded, if I Reset the LFG button, move it to the minimap, then /reload, it gets small and goes to the centre of the screen.

**Comment by teelolws** [comment]
I haven't been able to reproduce the issue of the LFG Button changing size - the size is supposed to be set by the Base UI via the options for the Menu:
![image](https://github.com/user-attachments/assets/ba4609b5-f8ce-44d3-a37b-6cdf46b790a8)

However I did spot the issue of it moving around if you /reload while already queued for a dungeon. This should solve that.

**Comment by raysmith59** [comment]
... I had no idea that Eye Size slider was in the Menu ... menu.  I had it set to 50% so that would explain why it became small although it going large when Reset in EME is an oddity.  Probably not worth doing anything about, though.  Thanks much!
