### ISSUE TITLE
Enhancement: Resize the Achievements notifications

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#135]
Might just be how spammy this notification is in Remix but I'd like them to be smaller, I'd appreciate a scale slider if possible for this frame.

**Comment by raysmith59** [comment]
Much love, thanks!

**Comment by raysmith59** [comment]
This might be less of an issue in retail but only the first achievement is resized, subsequent ones are back to full size.

**Comment by teelolws** [comment]
To fix that, I'll need to find an easily reproducable way to have multiple achievements pop up at the same time

**Comment by teelolws** [comment]
I've set the achievement alerts and the criteria alerts to resize. If you catch more that aren't resizing, can you show a screenshot, so I can get an idea of what to look for.

**Comment by raysmith59** [comment]
It looks like there are separate settings for achievements and loot; achievements are sized as expected but loot is still full size.

![HqGnjHTSAsWWtSIB](https://github.com/user-attachments/assets/8855bb96-94a1-4907-a6e0-ab092e9565e6)

Hopefully that shows up here, never tried to include a snip.

**Comment by teelolws** [comment]
I see, that system now handles all alerts, not just achievements, now. This should cover all the alert subtypes.

**Comment by raysmith59** [comment]
So far I haven't run into anything that wasn't handled, thanks again for the effort!
