### ISSUE TITLE
[Feature Request] BG Targets scale,

### ISSUE THREAD

**Issue by drsleo** [teelolws/EditModeExpanded#136]
As the title says, this is possible to scale Below minimap/BG targets frame and or you can add a scale to this frame would be wonderful.
and thank you your addon is amazing...

**Comment by teelolws** [comment]
Added the resize option. I can't confirm if it actually works though.

This is one of the frames that is disabled by default. You'll need to go into the addons options to enable support:
![image](https://github.com/user-attachments/assets/d91b4d18-495c-4898-8657-08f1abda0128)
