### ISSUE TITLE
Patch 11.0.2 Lua Error. Lua: 118: attempt to call global 'IsAddOnLoaded' (a nil value)

### ISSUE THREAD

**Issue by pollixx** [teelolws/EditModeExpanded#137]
Received this message today, when logging into WoW after the release of patch 11.0.2.

Message: ...terface/AddOns/EditModeExpanded/EditModeExpanded.lua:118: attempt to call global 'IsAddOnLoaded' (a nil value)
Time: Tue Aug 13 15:34:48 2024
Count: 1
Stack: ...terface/AddOns/EditModeExpanded/EditModeExpanded.lua:118: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@Interface/AddOns/EditModeExpanded/EditModeExpanded.lua"]:118: in function `callback'
[string "@Interface/AddOns/Blizzard_SharedXML/EventUtil.lua"]:55: in function `ContinueOnAddOnLoaded'
[string "@Interface/AddOns/EditModeExpanded/EditModeExpanded.lua"]:117: in main chunk

Locals: (*temporary) = nil
(*temporary) = "EditModeExpanded"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
addonName = "EditModeExpanded"
addon = <table> {
}

**Comment by teelolws** [comment]
Got it, thanks. I don't have much time for testing right now. Make another ticket if theres more issues.
