### ISSUE TITLE
Combo points bugged

### ISSUE THREAD

**Issue by Revontuletwow** [teelolws/EditModeExpanded#138]
There's a little bug in druid when changing forms, when i have the combo points on feral and i swap to guardian or boomie combo points are still showing and overlaping the ui.
![boomie](https://github.com/user-attachments/assets/8be140a1-f5d9-4836-9ee3-97ceae8241c1)

**Comment by teelolws** [comment]
Got it. This should stop that happening.

**Comment by Revontuletwow** [comment]
thank you so much !
