### ISSUE TITLE
ERROR OCCURED......

### ISSUE THREAD

**Issue by WingZeroMaster** [teelolws/EditModeExpanded#140]
308x ...eBlizzard_EditMode/Mainline/EditModeUtil.lua:37: bad argument #1 to 'abs' (number expected, got nil)
[string "=[C]"]: in function `abs'
[string "@Blizzard_EditMode/Mainline/EditModeUtil.lua"]:37: in function <...eBlizzard_EditMode/Mainline/EditModeUtil.lua:23>
[string "=(tail call)"]: ?
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:811: in function `UIParentManageFramePositions'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:183: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:169>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:841: in function `UIParent_ManageFramePositions'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:614: in function `UpdateBottomActionBarPositions'
[string "@Blizzard_EditMode/Mainline/EditModeManager.lua"]:508: in function `UpdateActionBarLayout'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:357: in function `UpdateVisibility'
[string "@Blizzard_ActionBar/Mainline/ActionBar.lua"]:324: in function `Hide'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:172: in function `Update'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:83: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = "number expected, got nil"

**Comment by teelolws** [comment]
`Blizzard_EditMode/Mainline/EditModeUtil`

Thats not my addon, thats something in the base UI doing that!
