### ISSUE TITLE
StatusBar:Hide() Error

### ISSUE THREAD

**Issue by LazarQt** [teelolws/EditModeExpanded#141]
I'm getting an error that the addons tries to call a protected function (StatusBar:hide()), afterwards the mana bar re-appears while being empty on login.

BugGrabberDB = {
    ["session"] = 8,
    ["lastSanitation"] = 3,
    ["errors"] = {
        {
            ["message"] = 'Interface/AddOns/NotEvenClose/core.lua:7: Usage: EmbedLibrary(addon, libname, silent, offset): \'libname\' - Cannot find a library instance of "AceComm-3.0".',
            ["time"] = "2024/08/26 20:39:48",
            ["locals"] = '(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): \'libname\' - Cannot find a library instance of "AceComm-3.0"."\n',
            ["stack"] = '[string "=[C]"]: ?\n[string "@Interface/AddOns/NotEvenClose/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:185: in function `EmbedLibrary\'\n[string "@Interface/AddOns/NotEvenClose/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:167: in function `EmbedLibraries\'\n[string "@Interface/AddOns/NotEvenClose/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:134: in function `NewAddon\'\n[string "@Interface/AddOns/NotEvenClose/core.lua"]:7: in main chunk',
            ["session"] = 1,
            ["counter"] = 1
        },
        {
            ["message"] = "[ADDON_ACTION_BLOCKED] AddOn 'EditModeExpanded' tried to call the protected function 'StatusBar:Show()'.",
            ["time"] = "2024/08/26 20:40:54",
            ["locals"] = '_ = Frame {\n}\nevent = "ADDON_ACTION_BLOCKED"\nevents = <table> {\n}\n',
            ["stack"] = '[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:485: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:485>\n[string "=[C]"]: in function `Show\'\n[string "@Interface/AddOns/Blizzard_TextStatusBar/Mainline/TextStatusBar.lua"]:96: in function `UpdateTextStringWithValues\'\n[string "@Interface/AddOns/Blizzard_TextStatusBar/Mainline/TextStatusBar.lua"]:82: in function `UpdateTextString\'\n[string "@Interface/AddOns/Blizzard_TextStatusBar/Mainline/TextStatusBar.lua"]:207: in function <...ns/Blizzard_TextStatusBar/Mainline/TextStatusBar.lua:206>\n[string "=[C]"]: in function `SetValue\'\n[string "@Interface/AddOns/Blizzard_UnitFrame/UnitFrame.lua"]:965: in function <Interface/AddOns/Blizzard_UnitFrame/UnitFrame.lua:945>',
            ["session"] = 3,
            ["counter"] = 2
        },
        {
            ["message"] = "[ADDON_ACTION_BLOCKED] AddOn 'EditModeExpanded' tried to call the protected function 'StatusBar:Hide()'.",
            ["time"] = "2024/08/26 20:46:58",
            ["locals"] = '_ = Frame {\n}\nevent = "ADDON_ACTION_BLOCKED"\nevents = <table> {\n}\n',
            ["stack"] = '[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:485: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:485>\n[string "=[C]"]: in function `Hide\'\n[string "@Interface/AddOns/EditModeExpanded/FrameHandlers/PlayerFrame.lua"]:42: in function <...ddOns/EditModeExpanded/FrameHandlers/PlayerFrame.lua:40>\n[string "=[C]"]: in function `Show\'\n[string "@Interface/AddOns/Blizzard_TextStatusBar/Mainline/TextStatusBar.lua"]:96: in function `UpdateTextStringWithValues\'\n[string "@Interface/AddOns/Blizzard_TextStatusBar/Mainline/TextStatusBar.lua"]:82: in function `UpdateTextString\'\n[string "@Interface/AddOns/Blizzard_UnitFrame/UnitFrame.lua"]:589: in function `UnitFrameManaBar_UpdateType\'\n[string "@Interface/AddOns/Blizzard_UnitFrame/UnitFrame.lua"]:980: in function `UnitFrameManaBar_Update\'\n[string "@Interface/AddOns/Blizzard_UnitFrame/UnitFrame.lua"]:375: in function `UnitFrameManaCostPredictionBars_Update\'\n[string "@Interface/AddOns/Blizzard_UnitFrame/UnitFrame.lua"]:214: in function `UnitFrame_OnEvent\'\n[string "@Interface/AddOns/Blizzard_UnitFrame/PlayerFrame.lua"]:101: in function `OnEvent\'\n[string "@Interface/AddOns/Blizzard_UnitFrame/UnitFrame.lua"]:1028: in function <Interface/AddOns/Blizzard_UnitFrame/UnitFrame.lua:1026>',
            ["session"] = 7,
            ["counter"] = 3
        }
    }
}

**Comment by teelolws** [comment]
You posted the error for some other addon
