### ISSUE TITLE
Hello, could you consider adding localization files for such a great plugin?

### ISSUE THREAD

**Issue by kaineoa** [teelolws/EditModeExpanded#144]
Hello, your plugin is fantastic, with rich features and a compact design, providing an excellent user experience. Thank you very much for creating this plugin.

I apologize for any unclear expressions due to my limited English proficiency.

If you are open to localizing it, I have a few suggestions for your consideration:

1,I noticed that some content in "Options.lua" under "desc" could be expressed more uniformly, since the "name" parameter already specifies what the module is, For example:
"Enables / Disables Holy Power support" and "Enables/ Disables Soul Shards support" = "Enables/ Disables Support"
"Enables / Disables additional options for the Target Frame" and "Enables / Disables additional options for the Focus Frame" = "Enables / Disables Additional Options"

2,Additionally, there is some text scattered in the "FrameHandlers" folder and "EditModeExpanded-1.0.lua". Have you considered including these in localization as well?

**Comment by teelolws** [comment]
I plan to do this when I get time.
