### ISSUE TITLE
Focus Cast Bar always showing

### ISSUE THREAD

**Issue by Stormrage2112** [teelolws/EditModeExpanded#145]
As it is... The Focus cast bar is alwyas active, even if focus is not casting.
If I set hide, it's always hiding.

**Comment by teelolws** [comment]
Does this happen with all other addons disabled?

**Comment by teelolws** [comment]
Quick self-test:
![image](https://github.com/user-attachments/assets/e621f12f-56b8-42d1-a0aa-3952a163c028)

![image](https://github.com/user-attachments/assets/ccb91e3e-5f34-473f-a4c8-148a832c35d3)
