### ISSUE TITLE
Hiding Talking Heads box also disables voice acting for those lines

### ISSUE THREAD

**Issue by james5272** [teelolws/EditModeExpanded#146]
This isn't so much a bug as it is a feature request.  I want to hide the talking head popup, but I still want to hear the voice.  As-is, hiding the talking head box disables voice for those lines as well, so you just get the line printed in the chat box.  Personally I still want to hear the lines, just not have the popup.  Is there a way to add this as an option?

**Comment by teelolws** [comment]
I can shove it off screen instead of actually hiding it, which should keep the sound playing. But not all players may want that. I'll have a think about how to handle it.

**Comment by teelolws** [comment]
Ok, I wasn't able to import your existing setting. After you update it, you'll need to set it back to hidden again, per your preference.
