### ISSUE TITLE
LUA error - TalkingHead.lua nil

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#147]
In the new version, happens every time I log in.

1x ...ddOns/EditModeExpanded/FrameHandlers/TalkingHead.lua:109: attempt to compare number with nil
[string "@EditModeExpanded/FrameHandlers/TalkingHead.lua"]:109: in function <...ddOns/EditModeExpanded/FrameHandlers/TalkingHead.lua:101>

Locals:
db = <table> {
}
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
shouldHideDialog = true
shouldMuteSound = nil
hideOnlyInCombat = nil

**Comment by teelolws** [comment]
Whoops.
