### ISSUE TITLE
Visibility option to only show bars on hover

### ISSUE THREAD

**Issue by z0mbat** [teelolws/EditModeExpanded#148]
I have a couple of bars with hearthstones, wormholes, engineering gadgets, special mounts and also a bar with consumables, but I only need to see them when I need them instead of taking up screen real estate all the time.

An extra visibility option to hide and only show certain bars on hover would be a great enhancement for this addon. I don't need to be able to set alpha values and other complex options, just a simple extra visibility option in the dropdown.

**Comment by teelolws** [comment]
Try this one: https://www.curseforge.com/wow/addons/blizzardbars-mouseover

If it doesn't work I can look into making my own version.
