### ISSUE TITLE
Rogue combo points missing

### ISSUE THREAD

**Issue by DakHarding** [teelolws/EditModeExpanded#150]
In retail the EME latest update is hiding rogue combo points. Checked/unchecked/reset.. still hidden. Had to disable it completely for now to show up. FYI..

**Comment by teelolws** [comment]
Does it happen with all other addons turned off?

**Comment by DakHarding** [comment]
Yes.

**Comment by DakHarding** [comment]
I found them. For some reason they were moved to the almost bottom left the corner half off the screen behind the chat window. Very odd.

**Comment by teelolws** [comment]
Thats where the Reset button moves stuff if it can't find the original location.
