### ISSUE TITLE
Soul shards not showing 

### ISSUE THREAD

**Issue by Wispofisis** [teelolws/EditModeExpanded#154]
If I use the perl frames add on I cannot see my soul shards when I turn on the edit mode expanded addon. If I turn edit mode expanded off I can see my soul shards but then everything else I changed with my ui is reverted obviously. I just updated the addon before I launched the game and i can't see my soul shards still.

**Comment by teelolws** [comment]
zperl? Looks like they make a copy of the soul shard frame and hide the original. I'm not finding any issues running both addons:

![image](https://github.com/user-attachments/assets/febf7101-2ccf-4e6d-b384-c49316791c6b)

**Comment by Wispofisis** [comment]
I don't know what the problem is then. When I turn on edit mode expanded the soul shards disappear and reloading doesn't bring them back. Perl config frames have been having an issue since BFA where anytime I get in a vehicle or a cutscene happens the soul shards disappear also and I have to reload. Guess I'll try to leave a message there.

**Comment by teelolws** [comment]
Ok, tried Perl Classic Unit Frames, found the problem. This should fix it.
