### ISSUE TITLE
LFG eye thing sometimes shows up when it shouldn't

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#156]
I only started noticing this today; when I log in or reload it shows up for a while and then disappears at some point later for no obvious reason.  Doesn't happen when EME is disabled.

**Comment by teelolws** [comment]
Does it happen when other addons are turned off?

**Comment by raysmith59** [comment]
Yes, happens with only EME enabled as well.

**Comment by teelolws** [comment]
Okay, can you send me your saved variable file

**Comment by raysmith59** [comment]
Stripped out my toon names for privacy but I assume you can get what you need from it otherwise.
[EditModeExpanded.zip](https://github.com/user-attachments/files/17856498/EditModeExpanded.zip)

**Comment by teelolws** [comment]
Ok got it. Old version of the hide setting was slipping through.

**Comment by raysmith59** [comment]
Spiffy, thanks!
