### ISSUE TITLE
Achievement Frame Right of Center

### ISSUE THREAD

**Issue by pollixx** [teelolws/EditModeExpanded#19]
When I use this addon, it seems that the achievement frame is right of center. When I use it in the default layout, achievements, loot, etc show perfectly in the center. However, when I adjust the achievement frame with the addon, I notice that when I get an achievement, loot, etc is left of center. 

It seems that the movement of the frame works fine and the achievements, loot, etc appear fine until I do a /reloadui or logout and log back in. The achievement frame will stay where I move it, however, when an achievement or loot shows up then it is left of center. 

Using the reset button, puts it back right of center but then achievements and loot appear centered. I hope my screenshots explain better than how I tried to explain this. 

![achievement default layout](https://user-images.githubusercontent.com/42001836/200201591-37d3d7c2-9c42-4ae7-84c7-482f2f273f3c.png)
![achievement adjustment to center](https://user-images.githubusercontent.com/42001836/200201593-bdaa4151-d264-46b4-978c-1e0162436056.png)
![display after adjustment](https://user-images.githubusercontent.com/42001836/200201594-7b87ba76-7717-47e8-8add-9c739f1db976.png)

**Comment by teelolws** [comment]
Yeah the box you're seeing is just a rough guide. When you don't have any active loot or achievements to display, the frame shows as a tiny dot:

![image](https://user-images.githubusercontent.com/49792789/200202450-05c3cb93-a95d-4c0a-b5fb-0e0742d01156.png)

Its the little green square you can see just above my action bar. During Edit Mode, the addon increases it to 40px to look like this:

![image](https://user-images.githubusercontent.com/49792789/200202396-9e18b1eb-91cc-4e3f-8f71-a3f7ace50bdc.png)

But I felt that was still too small and increased it to 300x80.

I realise now that can be confusing, as the 300x80 is a display only - the actual frame is saved at the Bottom Left corner as is its usual 5x5 size.

Do you think 20x20 will be less confusing? So it looks like this during Edit Mode:
![image](https://user-images.githubusercontent.com/49792789/200202569-45908279-7de9-4239-a5c9-95a6fbb01e95.png)

Then an achievement pops up like this:

![image](https://user-images.githubusercontent.com/49792789/200202605-15942805-7913-4d7d-a800-fd5b7602c08b.png)

With the dot perfectly centered:
![image](https://user-images.githubusercontent.com/49792789/200202632-6aedc325-5a30-4a28-afb0-4c7c80a8bd57.png)
![image](https://user-images.githubusercontent.com/49792789/200202627-fa9abcf7-d736-4aee-89fa-0db460302966.png)

**Comment by teelolws** [comment]
So you don't have to go and hunt for loot, use this to test it: `/run AchievementAlertSystem:AddAlert(5394)`

**Comment by teelolws** [comment]
To help with positioning, I'm going to make it popup an achievement whenever you click the 20x20 dot:

![image](https://user-images.githubusercontent.com/49792789/200753830-f617c829-67ab-4bc9-aa74-fb2b94dffd3d.png)

**Comment by pollixx** [comment]
Thank you for this! Also your addon is a wonderful addition to the default UI experience. I like to keep it nice and simple and this addon does just that! Thank-you!
