### ISSUE TITLE
Separate Micro Menu from Backpack

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#2]
Planned, if its possible without causing problematic taint.

I'd like to make the Micro Menu and Backpack bars separate groups that can be moved around independently.

**Comment by dhaern** [comment]
Is this feature added in 10.0-002?? Im waiting to jump to this addon when this feature is ready. Thanks for your work.

**Comment by teelolws** [comment]
Nah not yet. Its my task for tomorrow!
