### ISSUE TITLE
Request: Make all frames movable with the arrow keys

### ISSUE THREAD

**Issue by Nillx** [teelolws/EditModeExpanded#20]
Heya, i love how i can fine tune the frames affected by this addon with the arrow keys, do you think you can expand that to all frames? Or it might cause issues?

**Comment by teelolws** [comment]
It might be possible, but changing the existing Edit Mode stuff is risky. If it causes blizzard errors I won't do it. I'll try it out.

**Comment by teelolws** [comment]
I'm most of the way there. I've got all the frames moving with arrow keys. I just have to find a way to save the changes into Blizzards Edit Mode profiles, hopefully without causing taint / errors.
