### ISSUE TITLE
Add TargetOfTarget frame to movable frames

### ISSUE THREAD

**Issue by PhenomDevel** [teelolws/EditModeExpanded#21]
Hey,

i really like to be able to move more frames around since i like a clean UI. 

I usually have my actionbars really close to the player and target frame. This makes problems with the PetFrame (which is already solved by the addon) and with the TargetOfTargetFrame (i belive it's called `TargetFrameToT` in the frame stack).

Would be cool if you could add the TargetOfTargetFrame to the movable frames.

Cheers

**Comment by teelolws** [comment]
Hi, the Target of Target frame has the same problem as the Target Cast Bar frame: https://github.com/teelolws/EditModeExpanded/issues/10

Blizzards code moves it around, based on how many buffs/debuffs your target has. They replace the positioning I applied. If I try to blank out SetPoint to stop Blizzards code doing that, it leads to taint which can cause other problems.

**Comment by PhenomDevel** [comment]
That's unfortunate... You might aswell close the ticket then. Maybe Blizzard will either add this themselves or you find a way :P

**Comment by teelolws** [comment]
I'll close it when I've actually given up. I've still got a few ideas to try, and failing that I'm going to see if they change anything in 10.0.2 which makes it possible.
