### ISSUE TITLE
Achievements Missing?

### ISSUE THREAD

**Issue by alpineboi20** [teelolws/EditModeExpanded#24]
Hi there. Is the Achievement option missing for others, or is it just my end? Oh, and also totem seems to be gone too.

![Capture](https://user-images.githubusercontent.com/55804568/201495050-0561665e-65ea-43b0-9f58-d399268b80f9.PNG)

**Comment by teelolws** [comment]
The achievement frame is me not testing properly before this mornings patch. Pushing a fix for it now.

For the totem, though. I've set it to only show if you're playing a Paladin or Shaman. They're the only classes I'm aware of that actually use the thing.

**Comment by alpineboi20** [comment]
Thank you for the quick fix, much appreciated. :)
