### ISSUE TITLE
Soul Shard Position is reset when TotemFrame updates

### ISSUE THREAD

**Issue by PhenomDevel** [teelolws/EditModeExpanded#26]
Can be tested on Affliction Warlock with `Summon Darkglare` talented.

The position of the class resource (can be tested with other classes than warlock aswell e.g. mage with `Rune of Power`)

When the event `PLAYER_TOTEM_UPDATE` is triggered it causes a repositioning of the `TotemFrame` + `PlayerFrameBottomManagedFramesContainer` which causes the resources to be place below the `PlayerFrame` again.

**Comment by teelolws** [comment]
Its also resetting the Soul Shard frame back to the portrait when I /reload
