### ISSUE TITLE
Soul Shard position changes once you leave edit mode

### ISSUE THREAD

**Issue by PhenomDevel** [teelolws/EditModeExpanded#27]
When you move for example the Soul Shard frame around and close the edit mode it will be slighly lower positioned. This is a problem when you want to positon the frames really close next to erach other since they maybe overlapping afterwards.

**Comment by teelolws** [comment]
I have some code that makes each Edit Mode selection box a minimum of 40 pixels, for visibility. I see that doesn't play nicely with the Soul Shard frame. Its default is 101 x 24. I'll override it, allowing it to stay 101x24 during Edit Mode.

**Comment by PhenomDevel** [comment]
This might be a problem for other resources aswell. I am not sure how tall they are. E.g. Arcane Mage Orbs / DK Runes etc.

**Comment by teelolws** [comment]
Yeah I'll keep it in mind if I implement those ones. Noone has asked for them yet though :x
