### ISSUE TITLE
Soul Shard is always bottom left when checkbox is disabled

### ISSUE THREAD

**Issue by PhenomDevel** [teelolws/EditModeExpanded#30]
If i decide to not use one of the frames they seem to position somewhat hardcoded. If e.g. Soul Shard is disabled they will always be in the bottom left corner. I haven't found a way to get them back to the player frame except disabling the addon.

**Comment by teelolws** [comment]
The checkbox doesn't mean it'll disable it, that is to hide it during edit mode. It should still position off where you placed it before unchecking the box.

**Comment by PhenomDevel** [comment]
Well, could it be possible to add a simple enabled/disabled checkbox, so one can decide whether or not EME should reposition the corresponding frame?

**Comment by PhenomDevel** [comment]
Yeah that is totally fine. I don't want to enable/disable it on a regular basis.

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/201785156-6e89215a-fc0d-421a-9de5-23afcfb5c289.png)
![image](https://user-images.githubusercontent.com/49792789/201785179-99bc1ae3-eacb-42ed-9d79-0bfc7014bca3.png)

![image](https://user-images.githubusercontent.com/49792789/201785213-d4ccefc6-5659-4cab-91ae-ed7cb034c0b6.png)
![image](https://user-images.githubusercontent.com/49792789/201785229-214808aa-844f-453b-bd7f-082c5358e8be.png)
![image](https://user-images.githubusercontent.com/49792789/201785245-38f840e5-2e9a-4a22-8a60-fd5ef1645a6c.png)
