### ISSUE TITLE
New update problems

### ISSUE THREAD

**Issue by nawindie** [teelolws/EditModeExpanded#31]
When you install the new update "EditModeExpanded-10.0-020.zip" addon dont work. I tried to reinstall it and nothing, try to install previous version and work but when you update stop working. Probably the new update has some problem when you install it

**Comment by teelolws** [comment]
Hi,

Version 20 contains changes to support todays patch 10.0.2 and will not work on 10.0.0. If your region hasn't patched yet, you should stay on Version 19 until it does.

**Comment by nawindie** [comment]
oohhh, okay, probably this is the problem, thank you for that
