### ISSUE TITLE
Request: CompactRaidFrameManager

### ISSUE THREAD

**Issue by Revnn** [teelolws/EditModeExpanded#36]
Hi, thanks for this addon but i have a request, i'd love to be able to move this frame:
CompactRaidFrameManager

https://imgur.com/K2jlRkL

Thanks in advance

**Comment by teelolws** [comment]
Might not be possible, unfortunately.

![image](https://user-images.githubusercontent.com/49792789/202672825-f1d0655a-66b8-40ee-87cb-78573b06d043.png)

I'll have to set aside a decent length of time to study what is causing that taint, when its added to Edit Mode.

**Comment by Revnn** [comment]
That's very sad :< I wanted to keep my ui as clean as possible.
Would it be possible for you to make an option to hide it though?

**Comment by teelolws** [comment]
The problem is the raid frames are tied to that frame manager. I can't interfere with the frame manager without tainting the raid frames.

Theres probably a way, its on my list to find a solution.

**Comment by teelolws** [comment]
Okay, heres what I'm trying. When you click the Raid Frame Container, a second dialog will popup like this:

![image](https://user-images.githubusercontent.com/49792789/202828253-6f51deaf-b9b8-4f50-a1fb-3598a9baf9d0.png)

I can't hide the frame manager, but I can shunt it off the side of the screen. The consequence is you will need to manually position the Party Frames and the Raid Frames during Edit Mode, otherwise they'll pin to the bottom left corner.

It needs further testing. I'll publish an Alpha build soon.

**Comment by Revnn** [comment]
Thanks man, its working fine, not perfect since  every time I enter edit mode I have to position the raid again but its saving normally so that's a win for me, great job.

**Comment by Revnn** [comment]
I don't want to create another thread so I'm gonna use this one.
Would it be possible to make the exp bar to move outside screen bounds?
I have a weak aura that I'm able to set Y-offset to -5 and it fit perfectly on my screen.
You can import from here:
https://www.reddit.com/r/wow/comments/ye6g77/weakaura_to_move_the_parts_of_the_ui_you_cant/

When I installed your addon it broke that function, so the exp bar is a little higher than normal.
Here are the examples:
https://imgur.com/o9GQQqm

First bar using your addon and second with it disabled.
Thanks again mate.

**Comment by teelolws** [comment]
> Edit: Or maybe even an option to disable to exp option from your addon, since I can use that WA to move and resize.

Check the interface options. 

![image](https://user-images.githubusercontent.com/49792789/202920762-af934fb6-e17f-41ae-a977-04030f928b2a.png)

**Comment by Revnn** [comment]
oh wow, I'm dumb didn't even know there were interface options lol, thanks mate.
