### ISSUE TITLE
Bug: With settings?

### ISSUE THREAD

**Issue by nancikennedy** [teelolws/EditModeExpanded#38]
On Retail, using the latest version of EME, upon logging in:

4x ...d/libs/EditModeExpanded-1.0-24/EditModeExpanded-1.0.lua:562: attempt to index field 'settings' (a nil value)
[string "@EditModeExpanded/libs/EditModeExpanded-1.0-24/EditModeExpanded-1.0.lua"]:562: in function `func'
[string "@EditModeExpanded/libs/EditModeExpanded-1.0-24/EditModeExpanded-1.0.lua"]:1032: in function <...d/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:942>

Locals:
db = <table> {
}
(*temporary) = nil
(*temporary) = 12
(*temporary) = "attempt to index field 'settings' (a nil value)"
framesDB = <table> {
 13 = <table> {
 }
 15 = <table> {
 }
 3 = <table> {
 }
 14 = <table> {
 }
 16 = <table> {
 }
}
frame = CompactRaidFrameContainer {
 0 = <userdata>
 GetUnitFrame = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:315
 UpdateMagnetismRegistration = <function> defined @FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:411
 systemInfo = <table> {
 }
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:469
 ApplyToFrames = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:115
 SetFlowSortFunction = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:89
 SetBorderShown = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:110
 ReadyToUpdate = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:132
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:148
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:355
 displayPets = true
 SelectSystem = <function> defined =[C]:-1
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:489
 UpdateSystemSettingUseLargerFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:971
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:322
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @FrameXML/EditModeSystemTemplates.lua:244
 AddFlaggedUnits = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:274
 flowFilterFunc = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager.lua:523
 EMEanchorTo = UIParent {
 }
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:268
 OnLoad = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:14
 Layout = <function> defined @SharedXML/LayoutFrame.lua:333
 settingDisplayInfoMap = <table> {
 }
 GetSettingValueBool = <function> defined @FrameXML/EditModeSystemTemplates.lua:259
 TryUpdate = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:126
 OnSizeChanged = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:63
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:90
 UpdateSelectionVerticalState = <function> defined @FrameXML/EditModeSystemTemplates.lua:1084
 AddUnitFrame = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:303
 AddPets = <function> defined @Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua:251
 dirtySettings = <table> {
 }
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:288
 hasActiveChanges = false
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:948
 UpdateSystemSettingSortPla

**Comment by teelolws** [comment]
And thats why the latest patch was an alpha! I knew I'd forgotten something. Thanks, update coming soon.

**Comment by nancikennedy** [comment]
Unfortunately, this seems to still be lurking around in a slightly different format. I am getting it on my mage every time I "zone in" after a teleport/portal spell OR traveling via normal in game portals.

5x ...d/libs/EditModeExpanded-1.0-24/EditModeExpanded-1.0.lua:561: attempt to index field 'settings' (a nil value)
[string "@EditModeExpanded/libs/EditModeExpanded-1.0-24/EditModeExpanded-1.0.lua"]:561: in function `IsFrameMarkedHidden'
[string "@EditModeExpanded/EditModeExpanded.lua"]:281: in function <EditModeExpanded/EditModeExpanded.lua:280>
[string "=[C]"]: ?

Locals:
self = <table> {
 RegisterMinimapPinnable = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1087
 RegisterHideable = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:543
 RegisterFrame = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:152
 SetDefaultSize = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:478
 IsFrameEnabled = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:577
 RepositionFrame = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:494
 IsFrameMarkedHidden = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:558
 RegisterResizable = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:521
 IsRegistered = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:569
 SetDontResize = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:487
 RegisterCustomCheckbox = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:585
}
frame = TalkingHeadFrame {
 0 = <userdata>
 OnPostShow = <function> defined @FrameXML/AlertFrameIntrinsic.lua:4
 SetExternallyManagedOutroAnimation = <function> defined @FrameXML/AlertFrameIntrinsic.lua:28
 UpdateMagnetismRegistration = <function> defined @FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:411
 GetSettingValue = <function> defined @FrameXML/EditModeSystemTemplates.lua:252
 systemInfo = <table> {
 }
 GetCombinedSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:387
 ClearAllPointsBase = <function> defined =[C]:-1
 isClosing = false
 isBottomManagedFrame = true
 OnShow = <function> defined @FrameXML/UIParent.lua:2461
 dirtySettings = <table> {
 }
 OnDragStop = <function> defined @FrameXML/EditModeSystemTemplates.lua:574
 layoutParent = UIParentBottomManagedFrameContainer {
 }
 settingMap = <table> {
 }
 UpdateSystemSettingValue = <function> defined @FrameXML/EditModeSystemTemplates.lua:131
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:363
 IsVerticallyAlignedWithFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:328
 FadeinFrames = <function> defined @FrameXML/TalkingHeadUI.lua:57
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:148
 ConvertSettingDisplayValueToRawValue = <function> defined @FrameXML/EditModeSystemTemplates.lua:95
 ShouldShowSetting = <function> defined @FrameXML/EditModeSystemTemplates.lua:284
 SetSnappedToFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:437
 SelectSystem = <function> defined =[C]:-1
 savedSystemInfo = <table> {
 }
 OnManagedAlertFrameVisibilityChanged = <function> defined @FrameXML/AlertFrameIntrinsic.lua:20
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:489
 ClearDirtySetting = <function> defined @FrameXML/EditModeSystemTemplates.lua:127
 IsInitialized = <function> defined @FrameXML/EditModeSystemTemplates.lua:227
 UpdateSystemSetting = <function> defined @FrameXML/EditModeSystemTemplates.lua:213
 SetAlertContainer = <function> defined @FrameXML/AlertFrameIntrinsic.lua:12
 EMESystemID = 16
 NameFrame = Frame {
 }
 EMEanchorTo = UIParent {
 }
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:322
 RemoveSnappedFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:427

**Comment by teelolws** [comment]
Can you try the fix I just published there ^

**Comment by nancikennedy** [comment]
And squashed again =D
