### ISSUE TITLE
Defect: Bartender4 compatiblity issues

### ISSUE THREAD

**Issue by nancikennedy** [teelolws/EditModeExpanded#39]
I use Bartender 4 to move the LFG & Experience Bars. EME activates move mode on all the Bartender objects, but EME was adding it's own LFG & XP bar objects as well as unlocking the B4 ones so they could be repositioned. Not positioning them together results in a random precedent for where the bars end up. I ended up having to uncheck those options in the EME settings window, and just positioning with the B4 objects. I'm not sure if this is intended behavior that just isn't explicitly stated in the addon description, an EME problem or a Bartender4 one.

**Comment by teelolws** [comment]
Hi, you probably shouldn't run both addons. As far as I know, theres nothing this addon does that Bartender4 doesn't already do. Its just for players who want to do it during Edit Mode, instead of getting Bartender to do it.

**Comment by nancikennedy** [comment]
Vehicle Seats, Achievements, Target of Target, Target Cast Bar and Focus Cast Bar aren't something Bartender4 touches. I installed EME to access those things. :)

**Comment by teelolws** [comment]
Interesting.

Check out the interface options. Disable all the frames you don't want EME touching, then /reload:
![image](https://user-images.githubusercontent.com/49792789/202835527-cb42567a-f7ac-423d-ac8b-0edc19cfec33.png)

**Comment by nancikennedy** [comment]
Well, that never occurred to me. /facepalm
