### ISSUE TITLE
Save/Restore settings based on selected Edit Mode profile

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#4]
Planned feature: will base frame's positions based on the settings saved per Edit Mode profile.

It currently just uses a simple saved variable per character.

**Comment by Nillx** [comment]
This would be a great feature especially when playing on a multiple chars

**Comment by teelolws** [comment]
Latest update should provide this support. Needs more testing before I can publish it though.

**Comment by Nillx** [comment]
Thanks! It seems to work great, tested it on multiple characters and im not getting any errors. (Noticed a small issue with the minimap icon, it stayed visible after moving it but after a UI reload its all good.

**Comment by teelolws** [comment]
Yeah I'm having issues with that LFG button too. I'll keep trying.

**Comment by Nillx** [comment]
Regular character profiles are also fine to be honest (if this is too difficult to implement)
