### ISSUE TITLE
Request: 2 rows of 4 vertical groups with raid frames and 0 gap spacing option

### ISSUE THREAD

**Issue by james5272** [teelolws/EditModeExpanded#40]
Looking to replace Bartender4 with this mod and the new default UI.  However, a few adjustments I would need to do this:

1. Ability to set gap spacing to 0 instead of lowest being 2.  Bartender lets you do 0, I believe it even lets you go into the negatives (which I don't need).  For skills on action bars as well as for the bags spacing on the bag bar.

2. Old UI let you resize how far to the right vertical raid groups could draw, so you could limit to at most 4 per row, as little as 2 per row. for 2 rows of 4 vertical groups or 4 rows of 2 vertical groups.  New UI only lets you do 1 row of 8 groups.  Being able to adjust this again like old UI would be awesome.  My specific request is to get 2 rows of 4 vertical groups again, though more flexibility would be helpful for more users.

**Comment by PhenomDevel** [comment]
I just added support for changing the padding below the blizz standard in `BlizzHUDTweaks` in `1.16.2-beta` aswell. Maybe this can be helpful.

**Comment by teelolws** [comment]
With this update, I have added the option to set action bar padding to zero. I'm going to give it a day or so of testing, as long as I don't find any problems, I'll publish it.

As for your other request, moving the number of buttons per row and such is a bit beyond what I'm trying to do with this addon. Hopefully you can find someone else implementing it in their addon!
