### ISSUE TITLE
Request: Make Visablity Options for Action Bar 1 available

### ISSUE THREAD

**Issue by Tr4p** [teelolws/EditModeExpanded#41]
In the settings for all other Action Bars you can choose the Visability Option between:
- always visable
- in combat
- out of combat
- hidden

It would be nice if we could apply these to Action Bar 1 as well.

**Comment by teelolws** [comment]
I've been trying, but can't find a way to make it work without breaking other parts of the UI. It seems Blizz have made that Action Bar 1 an important part, where if its hidden, lots of other stuff hides and stops working, too.
