### ISSUE TITLE
Minimap Button Bag interaction

### ISSUE THREAD

**Issue by Harmonster** [teelolws/EditModeExpanded#43]
I get weird interaction with addon "Minimap Button Bag Reborn" when LFG-eye checked "pin to minimap"

MBBR trying to hide LFG-eye into folder. After moving LFG-eye, its place resetting to hide in folder again

Can you fix this?

**Comment by teelolws** [comment]
> Minimap Button Bag Reborn

ty, been wondering if that addon was going to get updated for DF

**Comment by teelolws** [comment]
I don't see a way I can make them compatible. Its probably better if you *dont* use "pin to minimap", and instead just make the LFG button 50% size and position it by the minimap where you want it during Edit Mode.

**Comment by Harmonster** [comment]
![image](https://user-images.githubusercontent.com/4973027/202932284-2afa077d-038d-45dd-b65e-08687342039c.png)

I still cant get it to work, icon still trying to be hided in folder. EME updated.

But thanks for the advice with position myself, i'll stick to it

**Comment by teelolws** [comment]
I don't think theres a way to make it *not* be hidden by MBB, other than not making it a minimap button at all. MBB collects everything attached to the minimap. I can't stop it.

**Comment by Harmonster** [comment]
> I don't think theres a way to make it _not_ be hidden by MBB, other than not making it a minimap button at all. MBB collects everything attached to the minimap. I can't stop it.

well, thanks anyway for trying and help

**Comment by teelolws** [comment]
I found a way to make it not be hidden by MBB. MBB actually has an internal list that used to mark the LFG button as an exception, so I'm going off that exception list.
