### ISSUE TITLE
When in Edit Mode the target castbar frame seems to be different from the actual castbar

### ISSUE THREAD

**Issue by PhenomDevel** [teelolws/EditModeExpanded#45]
When positioning the target castbar frame while in edit mode to e.g. line it up with the grid it works fine. Once you cast something it seems of. Maybe because of the icons or the header bar for the castbar.

**Comment by teelolws** [comment]
^ should sort that. lmk if it doesn't

**Comment by PhenomDevel** [comment]
Seems to work:)
