### ISSUE TITLE
Target Cast Bar

### ISSUE THREAD

**Issue by 3xtrem** [teelolws/EditModeExpanded#48]
Target cast bar by default is below target's buffs+debuffs, however, sometimes when in combat, the target cast bar appears to overlap with the target's buff instead, causing it to be difficult to see the cast bar as it is below the buffs. I attached an image for your convenience, hope it helps.
![image_2022-11-25_145958333](https://user-images.githubusercontent.com/23638654/203920565-fa18bdb6-acda-42ab-bb7e-8319341e724d.png)

**Comment by teelolws** [comment]
If you want it to move with the buffs, you'll have to leave it for Blizzard to handle. I can only put it at a specific position on your screen. I can't move it while you're in combat, only Blizzard can! And with their ability to move it comes the place they decide to put it.

To return it to Blizzard control, go into your Interface settings and turn off Target Cast Bar:
![image](https://user-images.githubusercontent.com/49792789/203921484-5163bd55-6d4a-44ad-8803-fc8b5cc3cce2.png)
