### ISSUE TITLE
Toggle to Hide a frame

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#5]
Once I figure out how to display a custom Settings box, I'll add an option to simply hide the selected frame. Maybe the player doesn't want the stock Menu Bar showing?

**Comment by Nillx** [comment]
What about an option that hides the frame but show it once you hover over it? Similar to the way Bartender do it?

**Comment by teelolws** [comment]
Hmm. Maybe.

**Comment by teelolws** [comment]
Toggle to Hide Frame done. Screenshots: https://github.com/teelolws/SLMicroMenu/issues/2#issuecomment-1304216422

**Comment by Nillx** [comment]
That looks great
