### ISSUE TITLE
Unchecking frames only hides them in edit mode

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#51]
I don't know if this is a usage issue or a bug but when I uncheck the Backpack frame when in edit mode, it disappears while I'm in edit mode but when I leave edit mode it comes back.  I expected it to be hidden outside of edit mode as well.

**Comment by teelolws** [comment]
Yes, thats the point of unchecking those. It behaves the same as the checkbuttons provided by Blizzard - it just shows/hides them during Edit Mode.

If you want to disable Edit Mode support for something completely, disable it through addon options:
![image](https://user-images.githubusercontent.com/49792789/205511697-c32a3db4-e46d-4e69-9389-4d131cdaf6de.png)

If you want to hide the frame, select the frame and check Hide:
![image](https://user-images.githubusercontent.com/49792789/205511719-9ec00822-d518-499e-a07f-dca15a5c8cd8.png)

If you aren't offered the Hide option, let me know what you want to hide and I'll see if its possible to add support.
