### ISSUE TITLE
Vehicle Seats and Durability not moveable

### ISSUE THREAD

**Issue by Rubyurek** [teelolws/EditModeExpanded#54]
Possible to fixe this? I can't them even move.

**Comment by teelolws** [comment]
Can you test it with all other addons turned off please

**Comment by Rubyurek** [comment]
I found the issue. Is Leatrix Plus

**Comment by teelolws** [comment]
Do you have these two options enabled?

![image](https://user-images.githubusercontent.com/49792789/210126279-7c415eee-4bae-4617-b431-fc59055d498f.png)

Two addons cannot both try to manage the same frame. You should be able to either disable Leatrix Plus support for managing those two frames, or disable EditModeExpanded support for managing those two frames.

See this page for instructions on disabling EME support for those frames: https://github.com/teelolws/EditModeExpanded/wiki/How-to:-Enabling---Disabling---Showing---Hiding
