### ISSUE TITLE
Error on disabling addon

### ISSUE THREAD

**Issue by SkrybeGH** [teelolws/EditModeExpanded#56]
Just tried EditModeExpanded and disabled the addon to check something. Reloading UI threw this error:

```
2x bad argument #1 to '?' (Usage: local accountInfo = C_BattleNet.GetAccountInfoByGUID(guid))
[string "=[C]"]: in function `GetAccountInfoByGUID'
[string "@FrameXML/SocialQueue.lua"]:171: in function `SocialQueueUtil_GetRelationshipInfo'
[string "@FrameXML/SocialQueue.lua"]:236: in function `SocialQueueUtil_HasRelationshipWithLeader'
[string "@FrameXML/QuickJoin.lua"]:408: in function `UpdateLeader'
[string "@FrameXML/QuickJoin.lua"]:391: in function `Update'
[string "@FrameXML/QuickJoin.lua"]:362: in function `UpdateAll'
[string "@FrameXML/QuickJoin.lua"]:352: in function `Init'
[string "@FrameXML/QuickJoin.lua"]:320: in function `UpdateAll'
[string "@FrameXML/QuickJoin.lua"]:42: in function <FrameXML/QuickJoin.lua:40>
[string "=[C]"]: in function `Show'
[string "@FrameXML/FriendsFrame.lua"]:77: in function `FriendsFrame_ShowSubFrame'
[string "@FrameXML/FriendsFrame.lua"]:396: in function `FriendsFrame_Update'
[string "@FrameXML/FriendsFrame.lua"]:345: in function `FriendsFrame_OnShow'
[string "@FrameXML/FriendsFrame.lua"]:465: in function <FrameXML/FriendsFrame.lua:463>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local accountInfo = C_BattleNet.GetAccountInfoByGUID(guid))"
```
If I open the friends list and go to the Quick Join tab while no one is active it throws the same error. While people are active (ie: there are groups I can quick join) that tab doesn't throw the error. Never seen this error before today, and it's only started since installing, and then disabling EditModeExpanded. 

Exited WOW completely and restarted and it doesn't seem to be throwing the error now.

**Comment by teelolws** [comment]
Hi, its unlikely my addon had anything to do with that error for two reasons:

1. Disabled addons can't do anything, and
2. The addon doesn't do anything to the Friends system.

It looks like people have been reporting that same error to Blizzard for years, and not getting a response or fix: https://us.forums.blizzard.com/en/wow/t/interface-framexml-socialqueue-lua-219/392274

Something to do with Battle.Net has a rare bug causing that error, and it unfortunately hit you when you disabled this addon. Appears to be coincidental.
