### ISSUE TITLE
Enhancement - Allow movement of storm tag at the top of the screen

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#60]
I'm currently in a storm area and I get an "Elemental Storm" indicator at the top of the screen, I'd like to be able to move that if possible.

**Comment by teelolws** [comment]
Hi, that is movable under "Subzone Information" in the addon. The one catch is you need to already be somewhere that has placed something into that field - somewhere that has given it some text. I can't force it to have a size during edit mode without causing errors.
