### ISSUE TITLE
Request: Smaller(thinner) padding around micro menu

### ISSUE THREAD

**Issue by Shackles70** [teelolws/EditModeExpanded#63]
I think padding is the term. 
I keep the micro menu in its default position, but I do scale it a bit to fit within my titan panel bar. The distance between the blue edit box and the actual icons will not allow me to push the icons to the very bottom of my screen.

**Comment by teelolws** [comment]
I'll look into an option to disable "clamp to screen".

**Comment by Shackles70** [comment]
That works too. TY

**Comment by teelolws** [comment]
With "clamp to screen" disabled, you may get issues if you change resolution. The frame can get lost off the edge of the screen, and will need the Reset button to bring it back.
