### ISSUE TITLE
Increase the size limits of resizable frames normally controlled by Blizzard

### ISSUE THREAD

**Issue by JFEspanolito** [teelolws/EditModeExpanded#68]
with today's update, I can no longer make the micro bar small and the bags can't be smaller than 75%... before I could :( I had everything at 50% because they get in the way...

Please fix the bug :c

**Comment by teelolws** [comment]
Hi, with todays patch, Blizzard took back control of the Micro Bar and Bags.

I can look into the possibility of changing those limits, but for the moment I no longer have control over those bars anymore.

**Comment by JFEspanolito** [comment]
Ok, thanks, i hope you can. love you <3

**Comment by teelolws** [comment]
Okay, first, you'll need to go into your addon options to turn the sliders on. I'm leaving them off by default so they don't replace Blizzards slider until the player wants it to:
![image](https://user-images.githubusercontent.com/49792789/214692930-a73aeb44-f9a3-4502-a0b1-bba2e51954d2.png)

I'm going to give it some time before releasing, incase I find problems with it fighting against the base UI. The code is this next commit if you want to test it.
