### ISSUE TITLE
Bug: Edit Mode Expanded DB Errors

### ISSUE THREAD

**Issue by EchoesFromBeyond** [teelolws/EditModeExpanded#70]
Hi there, Just leaving this as an error that's coming up. Thanks so much for your hard work!

`Message: ...d/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1107: attempt to index local 'db' (a nil value)
Time: Wed Jan 25 16:55:05 2023
Count: 1
Stack: ...d/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1107: attempt to index local 'db' (a nil value)
[string "@Interface/AddOns/EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua"]:1107: in function <...d/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1105>
[string "@Interface/AddOns/EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua"]:1121: in function <...d/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:1120>
[string "=[C]"]: in function `SetShown'
[string "@Interface/AddOns/EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua"]:643: in function <...d/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:625>
[string "=[C]"]: in function `ExitEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:208: in function <Interface/FrameXML/EditModeManager.lua:206>
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Interface/FrameXML/UIParent.lua"]:2899: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2930: in function `MoveUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2961: in function `HideUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2627: in function <Interface/FrameXML/UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3245: in function `HideUIPanel'
[string "@Interface/FrameXML/EditModeManager.lua"]:121: in function `onCloseCallback'
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:149: in function <Interface/SharedXML/SharedUIPanelTemplates.lua:144>
`

**Comment by teelolws** [comment]
Its something to do with the LFG button, and looks like it happened when you left edit mode? I've tried a few combinations but can't reproduce the issue. Can you tell me more about what you did before the error happened?
