### ISSUE TITLE
Suggestion: Focus Cast Bar and a Bug: Experience Bar

### ISSUE THREAD

**Issue by esruv** [teelolws/EditModeExpanded#71]
Is there anyway you can add support for the focus frame cast bar? also when I resize the experience bar and then go into the character frame and click on a rep and do "Show as experience bar" the bar is massive and doesnt get resized i think it has something to do with the new reputation bar option in default edit mode. 
![image](https://user-images.githubusercontent.com/77903716/214858775-6617a572-1594-4ca9-8aef-7d4cd43f3416.png)

**Comment by teelolws** [comment]
Focus Cast Bar is supported already. You need to enable Target and Focus to see it:
![image](https://user-images.githubusercontent.com/49792789/214924222-8fccbc36-57b0-4eff-8baa-c7789e237809.png)

If you don't see the bar, it might have slipped off the edge of your screen. Use the Reset button to get it back
![image](https://user-images.githubusercontent.com/49792789/214924330-4f970e84-d257-4ba4-a100-12df092532e9.png)

For the Experience Bar: Let me know if you still have problems after todays patch.
