### ISSUE TITLE
Some Text Error

### ISSUE THREAD

**Issue by Etern213** [teelolws/EditModeExpanded#76]
In https://github.com/teelolws/EditModeExpanded/blob/main/Source/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua#L939
`EditModeExpandedManagerFrame:ClearSelectedSystem()`
It should be 'EditModeManagerExpandedFrame', not 'EditModeExpandedManagerFrame'

It seems that this line has no practical use, so no error accur. Just change it when you change other things next commit.

**Comment by teelolws** [comment]
This should sort it. Its supposed to deselect the current frame when I close the option box, although I don't want it de-selecting default frames if I only close the EME option box. It was never calling that callback as I was resetting the OnClick script handler elsewhere.
