### ISSUE TITLE
Resize doesn't update position in the variables

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#82]
@Etern213 

Eg: resizable totem frame, before I make any changes, here it is sitting by the portrait frame:
![image](https://user-images.githubusercontent.com/49792789/226214105-bcedb1d6-93ea-44cb-abf2-fa93f0ad6e21.png)

I set it to 200%:
![image](https://user-images.githubusercontent.com/49792789/226214122-f22bb756-2d6a-4be4-9721-d654656efc5c.png)

/reload and its gone out of bounds, been moved to the top left:
![image](https://user-images.githubusercontent.com/49792789/226214141-cb83cbfa-9dd3-4a31-ace3-31d77d8b0d9f.png)

If I then manually move it, it saves the resized position into the variables and persists after a /reload
![image](https://user-images.githubusercontent.com/49792789/226214295-591a7e10-52d0-4df1-8b7b-bb286ba643d2.png)
![image](https://user-images.githubusercontent.com/49792789/226214171-a486a88a-129e-4e5d-9522-873b12644b3e.png)

This was a bug I previously fixed somewhere in that getOffsetXY mess. Needs to save the position after a resize is called without moving the frame.

**Comment by Etern213** [comment]
I found the reason.

See here https://github.com/Etern213/EditModeExpanded/blob/main/Source/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua#L937
`self` in line 937 refers to EditModeExpandedSystemSettingsDialog, not the frame we moved, So we should use `self.attachedToSystem:GetRect()` not `self:GetRect()`

**Comment by teelolws** [comment]
Cool, that worked!
