### ISSUE TITLE
I have some question about function EditModeExpandedSystemSettingsDialog:UpdateSettings

### ISSUE THREAD

**Issue by Etern213** [teelolws/EditModeExpanded#83]
The function is [here](https://github.com/teelolws/EditModeExpanded/blob/main/Source/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua#L793). It seems that this is copy and modified from [blizzard code](https://github.com/Gethe/wow-ui-source/blob/live/Interface/FrameXML/EditModeDialogs.lua#L400)

I was confused about how pool works, seems that variable settingFrame in function `UpdateSettings` is create by `settingFrame = settingPool:Acquire()`. I was thinking about when should we call function `UpdateSettings`, only once on init? or every time we change something.
When we already call it on init, and call it again in script [OnDragStop](https://github.com/teelolws/EditModeExpanded/blob/main/Source/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua#L255), will it create another settingframe or just use a old one?
If it create a new settingframe everytime we call `UpdateSettings`, I think we should call it more carefully, or there will be a lot of useless frame, and costs unnecessary resource.

After reading https://wowpedia.fandom.com/wiki/API_CreateObjectPool, I still don't know what 'pool' is. :(

**Comment by teelolws** [comment]
Sounds right. A 'pool' is a system for recycling frames instead of creating new ones.

**Comment by Etern213** [comment]
> Sounds right. A 'pool' is a system for recycling frames instead of creating new ones.

Got it, thanks a lot.
