### ISSUE TITLE
LFR icon isn't saving its position in 10.1

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#88]
I disabled all addons and the LFR icon won't stay in my usual spot for it (minimap border, similar to how it used to be), it keeps moving to the bottom of the screen and is always visible.

**Comment by teelolws** [comment]
Yeah the patch changed what its anchored to. I didn't get a chance to fix it on the PTR. Its on my list to fix!

**Comment by teelolws** [comment]
Okay this should sort it. Still some unexpected behaviour when selecting the option to pin it to the minimap, but it fixes after exiting edit mode.
