### ISSUE TITLE
LUA error after moving cast bar in 10.1

### ISSUE THREAD

**Issue by raysmith59** [teelolws/EditModeExpanded#89]
A cast bar addon I use broke with the patch so I moved the in-game cast bar into place and this error came up afterward.

1x EditModeExpanded/EditModeExpanded.lua:471: attempt to concatenate field 'systemName' (a nil value)
[string "@EditModeExpanded/EditModeExpanded.lua"]:471: in function <EditModeExpanded/EditModeExpanded.lua:470>
[string "=[C]"]: in function `UpdateSettings'
[string "@EditModeExpanded/libs/EditModeExpanded-1.0-60/EditModeExpanded-1.0.lua"]:143: in function <...d/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:142>
[string "=[C]"]: ?

Locals:
self = Frame {
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 Border = Frame {
 }
 GetSettingPool = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:913
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:123
 OnKeyDown = <function> defined @FrameXML/EditModeDialogs.lua:310
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:93
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:85
 UpdateSizeAndAnchors = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:751
 OnShow = <function> defined @SharedXML/LayoutFrame.lua:32
 Buttons = Frame {
 }
 OnDragStop = <function> defined @FrameXML/EditModeDialogs.lua:332
 dirty = false
 OnSettingInteractEnd = <function> defined @FrameXML/EditModeDialogs.lua:476
 UpdateButtons = <function> defined @FrameXML/EditModeDialogs.lua:447
 0 = <userdata>
 ReleaseAllNonSliders = <function> defined @FrameXML/EditModeDialogs.lua:375
 UpdateSettings = <function> defined =[C]:-1
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:114
 pools = <table> {
 }
 widthPadding = 40
 Settings = Frame {
 }
 AttachToSystemFrame = <function> defined =[C]:-1
 Title = FontString {
 }
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:73
 heightPadding = 40
 OnDragStart = <function> defined @FrameXML/EditModeDialogs.lua:328
 ReleaseNonDraggingSliders = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:924
 onCloseCallback = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:958
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:119
 OnLoad = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:957
 OnHide = <function> defined @FrameXML/EditModeDialogs.lua:303
 Layout = <function> defined @SharedXML/LayoutFrame.lua:351
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 RevertChanges = <function> defined @FrameXML/EditModeDialogs.lua:485
 OnSettingValueChanged = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:944
 CloseButton = Button {
 }
 UpdateDialog = <function> defined @FrameXML/EditModeDialogs.lua:358
 OnKeyUp = <function> defined @FrameXML/EditModeDialogs.lua:322
 MarkIgnoreInLayout = <function> defined @SharedXML/LayoutFrame.lua:44
 OnSettingInteractStart = <function> defined @FrameXML/EditModeDialogs.lua:467
 UpdateExtraButtons = <function> defined @EditModeExpanded/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.lua:763
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:347
}
frame = PlayerCastingBarFrame {
 0 = <userdata>
 InterruptSparkAnim = AnimationGroup {
 }
 GetEffectiveType = <function> defined @FrameXML/CastingBarFrame.lua:172
 playCastFX = true
 HideSpark = <function> defined @FrameXML/CastingBarFrame.lua:587
 ChargeFlash = Texture {
 }
 UpdateMagnetismRegistration = <function> defined @FrameXML/EditModeSystemTemplates.lua:654
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:532
 PlayFadeAnim = <function> defined @FrameXML/CastingBarFrame.lua:635
 systemInfo = <table> {
 }
 StopInterruptAnims = <function> defined @FrameXML/CastingBarFrame.lua:620
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:617
 BorderMask = MaskTexture {
 }
 downKeys = <table> {
 }
 SetLook = <function> defined @FrameXML/CastingBarFrame.lua:748
 UpdateStage = <function> defined @FrameXML/CastingBarFrame.lua:935
 resetToDefaultPosition

**Comment by teelolws** [comment]
Quick workaround until I can publish the fix: just turn off "show coordinates" for now.
