### ISSUE TITLE
Merge SLMicroMenu addon on this one?

### ISSUE THREAD

**Issue by dhaern** [teelolws/EditModeExpanded#9]
I didnt notice https://github.com/teelolws/SLMicroMenu is an addon from you and this one is amazing also. Do you have planned merge both addons in 1 adding SLMicroMenu as an EditModeExpanded option??

I think this is a good idea and we can save 1 addon.

**Comment by teelolws** [comment]
I don't plan to merge them, no. They have different purposes, and I prefer to give people the choice. They should not be forced into an all-or-nothing deal.

**Comment by dhaern** [comment]
Well adding it as an optional feature with a checkbox would be good but np. It's good anyways.

**Comment by teelolws** [comment]
Once I'm a bit further into making the Library part of this, I might look at adding the Library into SLMM. I'll need to create a way to make it not run twice, though.

**Comment by teelolws** [comment]
Ok done. 
![image](https://user-images.githubusercontent.com/49792789/199605792-cb12c019-185d-40f0-a80a-49da863c8952.png)
