### ISSUE TITLE
Assertion Failure

### ISSUE THREAD

**Issue by nancikennedy** [teelolws/EditModeExpanded#90]
Getting this error running, 10.1-002 on Retail:

3x ...d/libs/EditModeExpanded-1.0-62/EditModeExpanded-1.0.lua:95: assertion failed!
[string "=[C]"]: in function `assert'
[string "@EditModeExpanded/libs/EditModeExpanded-1.0-62/EditModeExpanded-1.0.lua"]:95: in function `RegisterFrame'
[string "@EditModeExpanded/EditModeExpanded.lua"]:843: in function <EditModeExpanded/EditModeExpanded.lua:259>

Locals:
(*temporary) = false

**Comment by teelolws** [comment]
Uh oh!

Looks like they changed the Combo Points frame in 10.1. They've combined the Rogue and Druid one and given it a new name.

**Comment by nancikennedy** [comment]
It looks like they made changes to most of the combo point-like stuff. I am noticing new art, etc.

**Comment by teelolws** [comment]
Fixed in: https://github.com/teelolws/EditModeExpanded/commit/6126c54b68d69f17b77af10ef5e54595242e09aa
