### ISSUE TITLE
LFG eye is missing.

### ISSUE THREAD

**Issue by NoShotz** [teelolws/EditModeExpanded#92]
Ever since 10.1.0 the LFG eye has been missing for me.

**Comment by teelolws** [comment]
Blizzard moved the LFG Eye in 10.1, and it may have been shoved off screen. Have you tried the Reset button?
![image](https://user-images.githubusercontent.com/49792789/236383963-ed266424-53d5-412e-b6f7-07fe753a214b.png)

**Comment by NoShotz** [comment]
I have tried it before posting this issue, and it didn't help.

**Comment by teelolws** [comment]
By default now, its "pinned" to your menu bar. Try moving your menu bar to the middle of the screen, save it, do a quick /reload, then reset the eye again.

**Comment by NoShotz** [comment]
> By default now, its "pinned" to your menu bar. Try moving your menu bar to the middle of the screen, save it, do a quick /reload, then reset the eye again.

If it is attached to the menu bar, no wonder I can't see it, cause I move the menu bar via the dominos addon, and I have it set at the top middle of the screen just under my broker bar. I don't see a way in dominos to be able to stop it from controlling it's location.

**Comment by teelolws** [comment]
I suggest you turn off dominos, reset and position the LFG eye where you want it, then turn dominos back on.

**Comment by NoShotz** [comment]
At this point it seems the issue is a dominos issue, cause when dominos is off, the queue status appears when I queue for stuff, but when I turn dominos on, it no longer appears no matter if this addon is turned on or not.

**Comment by teelolws** [comment]
Allright, I'll do some testing with dominos later, see if I can find a solution.

**Comment by NoShotz** [comment]
Yeah, it is definitely an issue with dominos, turned off every addon except for dominos, and the eye does not appear.

**Comment by teelolws** [comment]
Okay, not a fan of fixing an issue with someone elses addon, but here goes.
It seems Dominos doesn't have any method that I could find to reset a single frame. All I could find was an all-or-nothing deal.
So, this will go through your Dominos saved variables and reset its LFG Button settings.

`/run local function f(t) for k,v in pairs(t) do if k == "queue" then wipe(v) return end if type(v) == "table" then f(v) end end end f(DominosDB)`

Immediately `/reload` after this, and the LFG icon should be in the middle of your screen.

**Comment by NoShotz** [comment]
Yeah, that did indeed bring it on to the screen, but it wasn't centered which leads me to believe that the two mods trying to control the same UI element made it overshoot the screen bounds.

I fully understand not liking fixing other addons issues, if I knew it was a different addon causing the issue, I would have went there for help, but since the addon I moved the LFG eye with was this one, I assumed the issue was with this one.

Thanks for the help.

**Comment by teelolws** [comment]
I suggest you disable LFG Icon support in one of the addons, use the other addon for it. Not sure how to disable it in Dominos, but my option is under the usual Interface options -> Addons.
