### ISSUE TITLE
Vehicle seating UI does not show up in BGs

### ISSUE THREAD

**Issue by pt20223** [teelolws/EditModeExpanded#93]
When this addon is enabled (only addon), the vehicle bar showing seats in vehicles in BG does not show up.

**Comment by teelolws** [comment]
Strange condition. Only BGs? Shows up everywhere else?

**Comment by pt20223** [comment]
I haven't tested in any PvE content, I'm not really sure where content exists like that outside of a few quests.

**Comment by teelolws** [comment]
Blizzard changed the Vehicle UI in 10.1. You may have to reset it and reposition it.
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/b490daab-ca67-42d6-8642-997612bcecd3)

**Comment by pt20223** [comment]
Thanks, I think it did need reset, I haven't got vehicle BG yet to test, but I was able to see raid frame after resetting, my bad for missing that.
