### ISSUE TITLE
Raid Manager still bugged

### ISSUE THREAD

**Issue by Piskemannen** [teelolws/EditModeExpanded#94]
I don't get any error codes, but it's just a blank grey square with yellow arrow on it. Have tried to completely reinstall the addon, to no avail. It works fine when disabling this addon.

**Comment by teelolws** [comment]
Does it happen with all other addons disabled?

**Comment by Piskemannen** [comment]
Yes. I moved all addons out of the folder, so they're fully disabled.

**Comment by teelolws** [comment]
Can you share your edit mode profile string

**Comment by Piskemannen** [comment]
The Raid Manager doesn't show up at all, despite being checked in the Expanded section. Here's the UI:

0 36 0 0 0 7 7 UIParent 0.9 -0.0 -1 ##$$%-&&'%)$+$ 0 1 0 7 7 UIParent 0.8 38.3 -1 ##$$%-&&'%(#,# 0 2 0 6 6 UIParent 474.5 151.6 -1 ##$$%)&&'%(#,# 0 3 0 7 7 UIParent 500.0 -0.0 -1 #$$&%/&&'%(#,# 0 4 0 6 6 UIParent 473.8 -0.0 -1 #$$&%/&&'%(#,# 0 5 0 6 6 UIParent -0.0 276.7 -1 ##$$%/&('%(&,# 0 6 0 6 6 UIParent -0.0 276.7 -1 ##$$%/&('%(&,# 0 7 0 6 6 UIParent -0.0 277.5 -1 ##$$%/&('%(&,# 0 10 0 7 7 UIParent -225.7 178.4 -1 ##$$&('% 0 11 0 7 7 UIParent -335.2 0.8 -1 ##$$&&'%,# 0 12 0 6 6 UIParent 499.8 191.7 -1 ##$$&('% 1 -1 0 7 7 UIParent -352.7 139.5 -1 ##$#%# 2 -1 0 8 8 UIParent 0.0 -0.0 -1 ##$#%( 3 0 0 7 7 UIParent -352.7 145.8 -1 $#3# 3 1 0 7 7 UIParent 318.5 140.0 -1 %$3# 3 2 0 7 7 UIParent 318.1 -8.5 -1 %#&#3# 3 3 0 0 0 UIParent -0.0 0.0 -1 '$(#)$-#.#/#1$3# 3 4 0 0 0 UIParent -0.0 0.0 -1 ,%-#.#/#0#1#2( 3 5 0 2 2 UIParent -1985.3 -236.4 -1 &#*#3# 3 6 0 2 2 UIParent -1888.3 -236.9 -1 3# 3 7 0 7 7 UIParent -315.2 25.1 -1 3# 4 -1 0 7 7 UIParent -351.6 236.3 -1 # 5 -1 0 8 8 UIParent -240.7 201.4 -1 # 6 0 0 7 7 UIParent 5.4 83.5 -1 ##$$%#&/(')( 6 1 0 7 7 UIParent 0.9 165.3 -1 ##$$%#'0(&)( 7 -1 0 4 4 UIParent 0.0 522.5 -1 # 8 -1 0 6 6 UIParent 8.7 6.2 -1 #'$@%$&w 9 -1 0 6 6 UIParent 420.7 197.5 -1 # 10 -1 0 1 1 UIParent 0.3 0.0 -1 # 11 -1 0 8 8 UIParent 0.0 247.5 -1 # 12 -1 0 1 1 UIParent 947.2 -2.0 -1 #K$# 13 -1 0 8 8 UIParent 0.0 -0.0 -1 ##$#%#&- 14 -1 0 8 8 UIParent 0.0 -0.0 -1 ##$#%# 15 0 0 4 4 UIParent 0.0 591.5 -1 # 15 1 1 7 1 MainStatusTrackingBarContainer 0.0 0.0 -1 # 16 -1 0 7 7 UIParent -225.0 42.3 -1 #(

**Comment by teelolws** [comment]
To confirm: during Edit Mode, with this addon turned on, do you have this "Hide Frame Manager" option turned on?
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/60209d31-d6af-4652-bb47-17464a36b233)

Also, when you said the frame manager was " just a blank grey square with yellow arrow on it", this is what it is supposed to look like when its not expanded. The game just 'shoves' it mostly off screen so you only see the yellow arrow. When you click the arrow, it moves the rest of the "blank grey square" onto your screen and adds all the buttons to it.

But if the Raid Manager isn't showing up at all, theres a few possible reasons:

1. you're simply not in a raid group, so the game is hiding it
2. the "Hide Frame Manager" option is turned on (I admit, that option could be worded better)
3. the raid manager has been dragged completely off screen and we need to reset it back onto the screen again
4. another bug has happened that I have not found yet

**Comment by Piskemannen** [comment]
The addon has worked fine for months, up until sometime last week. So I should have Hide Frame Manager unchecked? Sometimes the group finder eye also appears, maybe it's related?

Even when I'm not in any group, if I open the Edit Mode clicking the arrow makes box on right appear, clicking it again, the left one appears. The photo is edited and these 2 boxes don't appear at the same time.

![1](https://github.com/teelolws/EditModeExpanded/assets/133789008/30a30c17-92a7-45e1-a4d7-49bb6827cad4)

**Comment by teelolws** [comment]
So, the "Hide Frame Manager" is an option someone else asked for, the ability to completely hide that box. Its attached to the raid frame, because it was added back before I added full Raid Manager support.

Yes, the box staying after leaving Edit Mode is a bug that will go away when you /reload. I will see if I can find a workaround for that.

But you should be able to drag it back to be mostly off screen. If it won't completely move offscreen, you can use the arrow keys to push it further. Or use the Reset button to move it back to where it was when you first logged in, before this addon started interfering.

**Comment by Piskemannen** [comment]
Hide Frame Manager definitely don't work for me, it shows up like that regardless of checked/unchecked. Maybe Blizzard did something with patch 10.1? I'm sure you will sort it out.

Btw have you considered adding more editing options, as there's several more widgets that would be nice to edit.

**Comment by teelolws** [comment]
If you have a widget in mind that you'd like to be able to move, feel free to name it. Keep in mind though, this addon (and Edit Mode) is meant for items that are usually on your screen most of the time. Its not for things like "popups" such as the collections window.

**Comment by Piskemannen** [comment]
Seems the Raid Manager stays every time I join a group, /reload fixes it until next time tho. Hmm you do have most necessary things in your addon already, but is a square minimap something that could be considered?

**Comment by teelolws** [comment]
A square minimap is an option I'd *like* to be able to provide, but its a very complex area that I don't know much about! With help from another dev I may be able to, or if I can see how other addons do it.

**Comment by Piskemannen** [comment]
I'm using this addon currently https://www.curseforge.com/wow/addons/basic-minimap

Maybe you can pick the code apart from that addon. I wonder how difficult it is to turn the default minimap from round to square, rather than making a new from scratch?

**Comment by teelolws** [comment]
Okay, this change should sort some of the bugs out around the raid manager continuing to show when it isn't supposed to. The option to hide it has been moved, and will need to be re-selected after updating the addon.

**Comment by teelolws** [comment]
And here is a basic implementation of a square minimap. Just changes the shape from circle to square, moves the big Expansion Features button, and hides the border. Nothing too complicated. If someone wants something more complicated, they're better off getting an addon designed for handling the Minimap, like the one you linked.

**Comment by Piskemannen** [comment]
Thanks for the update. Is it possible to add something like this? https://www.curseforge.com/wow/addons/minimapbuttonbutton as with square minimap, the buttons act as if its still a circle.

**Comment by teelolws** [comment]
I'm using MBB Reborn: https://www.curseforge.com/wow/addons/minimapbuttonbag-reborn-mmb-reborn it shows to the side. Yeah the button moves around the phantom circle, but its not much to just place it off to the side that overlaps like that.

![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/cb9817aa-a47e-4d44-a5fe-7bf279de942b)

**Comment by Piskemannen** [comment]
Fair enough, is there anything that can be done with the "Dragon Isles Summary" button in terms of resizing/move etc?

Also the square that says 3 on your minimap only shows 1 of my 20 addons I have installed, it acts almost like addon linked?

**Comment by teelolws** [comment]
That "3" is the new addon compartment frame. Its supposed to be the replacement for minimap buttons, hopefully more and more devs will start to use it over time: https://old.reddit.com/r/wow/comments/13a7hwf/addon_developers_please_start_using_the_new/

**Comment by Piskemannen** [comment]
So it's a Blizzard default? You'd think they could just slap every addon that shows up under addon list there, without the devs to manually add it. It's such a neat feature imo. 

Could you add a way to move the bag window (not icon)? For some reason it likes being like an inch from the botton of screen.

**Comment by teelolws** [comment]
Its not that simple. Not every addon wants to be listed. Not every addon has a minimap button. None of my addons have a minimap button - I have no reason for one. The buttons placed on the minimap is done by code written by addon authors, so the authors have to remove that code first. Then they have to provide code into the new Addon Compartment to tell it what to do when its button is clicked.

As for the bag window, I cannot move any of the "popup" frames like that one. Especially that one - it is clickable buttons so its very restricted. You'll need to look into an addon that completely replaces your bag frame with its own one.
