### ISSUE TITLE
Bonus Roll is missing

### ISSUE THREAD

**Issue by class2u** [teelolws/EditModeExpanded#95]
Hi, The Bonus Roll option does not show up in the side panel of EditMode. And no Bonus Roll frame on the screen. I have checked Bonus Roll option in the settings panel. Am I missing something? Thank you.

**Comment by teelolws** [comment]
Hi, I just added a wiki page explaining this one: https://github.com/teelolws/EditModeExpanded/wiki/Bonus-Roll-Frame
