### ISSUE TITLE
Auction Multisell

### ISSUE THREAD

**Issue by teelolws** [teelolws/EditModeExpanded#98]
![1](https://github.com/teelolws/EditModeExpanded/assets/134382673/e9d15dde-59e7-4e36-887c-da6f29beaf74)

I double checked. It should not be an addon. It appears when you sale more than one, If you sale dozens of the same item, it shows the progress. The frame shows the progress and appears for a short time.

_Originally posted by @LLeonLeung in https://github.com/teelolws/EditModeExpanded/issues/97#issuecomment-1560466539_

**Comment by teelolws** [comment]
Got it. This one will have similar restrictions: won't be able to move it until you've opened the auction house and triggered a multisell since your last login or /reload.

**Comment by LLeonLeung** [comment]
This quite difficult to lock the frame, you can not open the auction house when you under edit mode.

**Comment by teelolws** [comment]
You just need to *have had it open* at some point, and triggered the multisell dialog. After that it will show as a box in edit mode - there won't be anything in the box, it'll just be a blank box that says "Auction Multisell" when you click on it.

**Comment by LLeonLeung** [comment]
Thanks. I tried your new updated lua file, it seemed doesn't work well as you mentioned above.

**Comment by teelolws** [comment]
You might have to move your action bars out of the way to see it. This is what it looks like after I've listed 2 of the same item on the auction house:

![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/71111731-8700-4ba3-8e1d-6ba2bd4935ed)

**Comment by LLeonLeung** [comment]
That's strange, nothing shows in expanded list and no frame could be selected after I triggered the multisell dialog.
![24](https://github.com/teelolws/EditModeExpanded/assets/134382673/d722232a-ff8e-4210-996f-604d0fab490a)

**Comment by LLeonLeung** [comment]
![25](https://github.com/teelolws/EditModeExpanded/assets/134382673/b9a4c781-658e-4b92-9376-05a06161a4fb)

**Comment by teelolws** [comment]
Did you /reload after you selected this?
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/a1b4d4b5-c7a1-4218-9951-b86144d3ebb5)

**Comment by LLeonLeung** [comment]
Yes, and I also tried restart the game

**Comment by teelolws** [comment]
Just tried it with all addons off. I'll try it with my game in chinese.

**Comment by teelolws** [comment]
Yeah I don't know what else to suggest. Maybe see if another addon is interfering?

![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/c9d52978-5a21-45e1-a940-ae74e2d3eeae)

**Comment by LLeonLeung** [comment]
Yes, you are right. Maybe Bartender4. When I closed Bartender4, the progress frame show in the right place. But even though I closed Bartender4, the multi-sell option doesn't show in the expanded list. Even though I closed all the addon.

**Comment by teelolws** [comment]
See if you're getting any addon errors:

/console scriptErrors 1

**Comment by LLeonLeung** [comment]
Nothing, and I reloaded nothing errors too.

**Comment by LLeonLeung** [comment]
The trigger is I list the same item more than 2 in AH, right? After that, it should show in the expanded list.

**Comment by teelolws** [comment]
Yeah if that graphic shows, its supposed to capture it for the rest of the session
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/4f1a3839-b0bc-4f47-ac63-4edeecfff053)

**Comment by LLeonLeung** [comment]
Sorry, last question, can the trigger change to the same as achievements？

**Comment by teelolws** [comment]
The achievements is supported, its a little dot you might have to find:
![image](https://github.com/teelolws/EditModeExpanded/assets/49792789/b5e14a74-d046-45b9-b9b9-b097837594dc)

**Comment by LLeonLeung** [comment]
Yes, I know. I mean the trigger for Auction Multisell change to the same trigger as achievements.

**Comment by teelolws** [comment]
No they're different systems, different frames, different anchor points. Theres no connection.

**Comment by LLeonLeung** [comment]
Understood, thanks for your response all the time.

**Comment by LLeonLeung** [comment]
Hi teelolws, I downloaded the updated version from curse,, now it works. Great thanks for your help.

**Comment by Piskemannen** [comment]
Hey teelolws, after the latest update I can't adjust size of the lfg eye anymore. Tried a fresh install, with no other addons running.
